import {api,local,ApiError} from './storage.js';
import {dist} from './engine/math.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const date=v=>v?new Date(v).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'未提供';
const short=(v,n=110)=>[...String(v||'')].length>n?[...v].slice(0,n).join('')+'…':v||'';
const paths={leaf:'M12 20V4m0 8C5 12 3 7 5 3c5 0 7 4 7 9Zm0 5c7 0 9-5 8-9-5 0-8 4-8 9Z',bag:'M6 8h12l2 12H4L6 8Zm3 0V6a3 3 0 0 1 6 0v2m-5 5h4',journal:'M5 3h14v18H5V3Zm4 0v18m3-12h4m-4 4h4',synthesis:'m12 3 3 6 6 3-6 3-3 6-3-6-6-3 6-3 3-6Z',phone:'M5 21V7a7 7 0 0 1 14 0v14M3 21h18M8 8h8v10H8V8Zm2 4h4',home:'m3 10 9-7 9 7M5 9v12h14V9m-9 12v-7h4v7',compass:'m16 8-3 5-5 3 3-5 5-3ZM12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Z',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm0-6v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',map:'m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Zm6-2v16m6-14v16',close:'m6 6 12 12M6 18 18 6',arrow:'M4 12h16m-6-6 6 6-6 6',anchor:'M12 3v16M8 7h8M4 14a8 8 0 0 0 16 0m-16 0v4m16-4v4',read:'M12 6C9 3 5 3 2 4v15c4-1 7-1 10 2m0-15c3-3 7-3 10-2v15c-4-1-7-1-10 2V6Z'};
const icon=(name,size=20)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.leaf}"/></svg>`;
let savedSettings;try{savedSettings=JSON.parse(localStorage.getItem('ww-settings')||'{}')}catch{savedSettings={}}
// Retire the old preference without changing any visitor identity or saved content.
if(!savedSettings||typeof savedSettings!=='object'||Array.isArray(savedSettings))savedSettings={};
delete savedSettings.mode2d;
if(new URLSearchParams(location.search).get('mode')==='2d'){const u=new URL(location.href);u.searchParams.delete('mode');history.replaceState({},'',u.pathname+u.search+u.hash)}
const s={page:'landing',modal:null,world:null,journey:null,field:null,returnContext:null,contentMap:new Map(),bag:[],anchors:[],presets:[],session:null,selected:new Set(),readonly:false,saveState:'正在连接',pending:0,settings:{quality:'medium',sensitivity:1,reduceMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,invertY:false,autoQuality:true,sound:false,volume:.18,textSize:16,...savedSettings},busy:false};
let engineCreation=null,recoveryCheckpoint=null,needsCanvasReset=false;
const rendererPreference=new URLSearchParams(location.search).get('renderer')==='legacy'?'legacy':'three';
const localQA=['127.0.0.1','localhost'].includes(location.hostname)&&new URLSearchParams(location.search).get('qa')==='1';
let engine=null,saveQueue=Promise.resolve(),lastTrigger=null,jobToken=0,eventsBuffer=[],flushing=false,expanding=false,activeContent=null,modalId=0,contextNode=null;
let diagnostics={fps:0,drawCalls:0,triangles:0};
let sceneIntent=0;
function beginSceneIntent(){engine?.cancelSceneLoad?.();return ++sceneIntent}
function currentIntent(id){return id===sceneIntent}
function pushRoute(path){const u=new URL(path,location.origin);if(rendererPreference==='legacy')u.searchParams.set('renderer','legacy');if(localQA)u.searchParams.set('qa','1');history.pushState({},'',u.pathname+u.search)}


function toast(text,error=false){let div=document.createElement('div');div.className='toast'+(error?' error':'');div.textContent=text;$('#toasts').append(div);while($('#toasts').children.length>2)$('#toasts').firstElementChild.remove();setTimeout(()=>div.remove(),4500)}
function modeBadge(mode=s.world?.dataMode||'demo',inline=false){return `<span class="mode-badge ${mode==='demo'?'demo':''} ${inline?'inline':''}">${mode==='demo'?'原创演示 · 非知乎数据':mode==='cached'?'真实来源 · 缓存快照':'真实来源 · 本次获取'}</span>`}
function setSave(v){s.saveState=v;let el=$('#save-label');if(el)el.textContent=v}
function applySettings(){localStorage.setItem('ww-settings',JSON.stringify(s.settings));document.documentElement.style.setProperty('--ui-size',s.settings.textSize+'px');if(engine)engine.settings={...s.settings};document.body.classList.toggle('reduced-motion',s.settings.reduceMotion)}
function brand(){return `<a class="brand" href="/" data-action="brand"><img src="/static/assets/mark.svg" alt=""><span><strong>漫知录</strong><small>WANDERWISE</small></span></a>`}
function button(action,label,cls='btn',other=''){return `<button type="button" class="${cls}" data-action="${action}" ${other}>${label}</button>`}
function header(){return `<header class="header">${brand()}<div class="header-actions"><span class="save-status"><span class="save-dot ${s.pending?'pending':''}"></span><span id="save-label">${esc(s.saveState)}</span></span>${button('credits','关于漫知录','text-btn')}${button('settings',icon('settings'),'icon-btn','aria-label="设置"')}${s.page!=='landing'&&s.page!=='home'?button('pause',icon('home'),'icon-btn','aria-label="保存与回家"'):''}</div></header>`}
function dock(){let home=s.page==='home';return `<nav class="bottom-dock" aria-label="主要功能">${button('bag',icon('bag')+`知识行囊 <span class="counter">${s.bag.length}</span>`,'dock-item')}${button('journal',icon('journal')+'漫行者日志','dock-item')}${home?button('synthesis',icon('synthesis')+'思维合成台','dock-item'):button('map',icon('map')+'旅途地图','dock-item')}<span class="dock-divider"></span>${home?button('phone',icon('phone')+'同频电话亭','dock-item'):button('anchor',icon('anchor')+'留下想法','dock-item')}${home?button('seed',icon('compass')+'开始旅程','dock-item'):button(s.page==='field'?'return-world':'pause',icon('home')+(s.page==='field'?'返回主世界':'回家'),'dock-item')}</nav>`}
function render(){
 if(s.page==='landing'){
  $('#app').innerHTML=header()+`<div class="hero-badge">陆地漫游版 · LAND EDITION</div><main class="hero"><div class="eyebrow">A JOURNEY OF THOUGHT</div><h1>知识不止<br><em>一个方向。</em></h1><p class="desc">带着一个问题，走进思想的森林。<br>遇见观点，留下思考，<br>把路上的微光，带回自己的精神家园。</p><div class="button-row">${button('enter-home','走进我的小屋 '+icon('arrow'),'btn primary')}${button('journal','继续一段旅程','btn ghost')}</div><p class="hero-note">无需登录 · 私人存档 · 第三人称自由漫游</p></main><div class="hero-right">即使未见彼岸灯火<br>长路本身，已是圆满</div><footer class="hero-footer"><span>知乎黑客松 2026 · 校园新锐季<br>本地运行版 · 自带内容明确标记为演示</span><span>探索 · 收集 · 思考 · 沉淀</span></footer>`;return;
 }
 let home=s.page==='home',title=home?'欢迎回家，漫行者。':s.page==='field'?s.field?.title:s.world?.seedText;
 let subtitle=home?'这里存放的，不只是知识，还有你走过的路。':s.page==='field'?s.field?.coverageNote:(s.world?.notice||s.world?.semanticMethod);
 $('#app').innerHTML=header()+`<section class="scene-meta"><div class="eyebrow">${home?'YOUR INNER HOME':s.page==='field'?'THE READING FIELD':'THE FOREST OF IDEAS'}</div><h2>${esc(title)}</h2><div class="caption">${esc(subtitle)}</div>${home?'':modeBadge()+` <span class="caption">${date(s.world?.sourceFetchedAt)}</span>`}</section>${dock()}`+`<div id="target-box" class="target-box"></div><div class="roam-prompt" id="roam-prompt">${button('roam','进入漫游 '+icon('arrow'))}<small>${home?'走向大门，开始新的旅程':'WASD 移动 · 鼠标观察 · 空格跳跃 · Esc 解锁'}${s.readonly?' · 当前只读':''}</small></div><div class="roam-help"><kbd>E</kbd> 收集 <kbd>F</kbd> 深读<br><kbd>R</kbd> 想法 <kbd>V</kbd> 追踪<br><kbd>B</kbd> 行囊 <kbd>T</kbd> 锚点</div><div id="nav-label" class="nav-label hidden"></div><div id="diag" class="diag"></div>`;
 if(engine?.active&&!s.modal)onActive(true);updateNav();
}
function onActive(active){$('#roam-prompt')?.classList.toggle('hidden',active||!!s.modal);if(active&&engine?.target)onTarget(engine.target,dist(engine.player,engine.target.position));if(!active){let el=$('#target-box');if(el)el.innerHTML=''}}
function onTarget(t,d){if(!engine?.active)return;let el=$('#target-box');if(!el)return;let acts=t?.type==='facility'?'左键打开设施':t?.type==='excerpt'?'<kbd>左键</kbd> 打开原文 · 无需瞄准 <kbd>E</kbd> 收集 <kbd>R</kbd> 想法':d<=4?'<kbd>左键</kbd> 话题 <kbd>V</kbd> 追踪':'<kbd>V</kbd> 标记方向 · 靠近后可阅读';el.innerHTML=t?`<strong>${esc(t.type==='excerpt'?short(t.excerpt.text,38):t.title)}</strong><small>${acts}</small>`:''}
function updateNav(){let el=$('#nav-label'),nav=engine?.navigation;if(!el||!nav)return;let n=s.world?.nodes.find(n=>n.id===nav.id);el.classList.toggle('hidden',!nav.mode||!n);if(n)el.innerHTML=`${nav.mode===1?'思潮微风':'思想光路'} · ${esc(n.title)} ${button('cancel-nav','取消','mini-btn')}`}
function openPanel(type,title,subtitle,body,{size='',footer='',reader=false}={}){
 modalId++;lastTrigger=document.activeElement;engine?.pause();s.modal=type;$('#overlay-root').innerHTML=`<div class="modal-shell ${reader?'reader-shell':''}"><section class="panel ${size} ${reader?'reader':''}" role="dialog" aria-modal="true" aria-labelledby="panel-title"><header class="panel-head"><div><div class="eyebrow">${reader?'A MOMENT TO READ':'WANDERWISE / '+type.toUpperCase()}</div><h2 id="panel-title">${esc(title)}</h2>${subtitle?`<p>${esc(subtitle)}</p>`:''}</div>${button('close',icon('close',17),'icon-btn close','aria-label="关闭面板"')}</header><div class="panel-body">${body}</div>${footer?`<footer class="panel-foot">${footer}</footer>`:''}</section></div>`;
 onActive(false);setTimeout(()=>$('#overlay-root input:not([type=checkbox]),#overlay-root textarea,#overlay-root button')?.focus({preventScroll:true}),30)
}
function closePanel(){if(s.modal==='progress')return cancelProgress();if(s.modal==='reader'&&activeContent){queueEvent('content_closed',contextNode?.topicId);activeContent=null}s.modal=null;modalId++;$('#overlay-root').innerHTML='';lastTrigger?.isConnected&&lastTrigger.focus?.({preventScroll:true});onActive(false)}
function empty(title,copy){return `<div class="empty"><div class="empty-symbol">✧</div><h3>${esc(title)}</h3><div>${esc(copy)}</div></div>`}
async function fetchAll(path){let out=[],cursor=null;do{let result=await api.call(path+(path.includes('?')?'&':'?')+'limit=50'+(cursor?'&cursor='+encodeURIComponent(cursor):''));out.push(...result.items);cursor=result.nextCursor}while(cursor);return out}
async function refreshPrivate(){let offline=false;try{s.bag=await fetchAll('/bag');s.anchors=(await api.call('/anchors')).items;await local.put('cache',api.owner+':private',{bag:s.bag,anchors:s.anchors})}catch(e){if(e instanceof ApiError)throw e;let cache=await local.get('cache',api.owner+':private');if(cache?.value){s.bag=cache.value.bag;s.anchors=cache.value.anchors}else if(!s.bag.length&&!s.anchors.length)throw e;offline=true}engine?.setAnchors(s.anchors);s.pending=(await local.all('outbox')).filter(x=>x.value.owner===api.owner).length;setSave(s.pending?`${s.pending} 项待同步`:offline?'离线 · 已载入本机快照':'已保存到本机服务')}
async function home({skipPause=false}={}){
 if(s.journey?.status==='active'&&!skipPause){await pauseJourney();return}
 const intent=beginSceneIntent();closePanel();s.page='home';s.world=null;s.journey=null;s.field=null;s.returnContext=null;contextNode=null;s.readonly=false;
 if(engine&&await engine.setScene('home')===false)return;if(!currentIntent(intent))return;
 pushRoute('/home');await refreshPrivate();if(currentIntent(intent))render();
}
async function seedsPanel(){let real=s.presets.filter(p=>p.dataMode!=='demo'),demo=s.presets.filter(p=>p.dataMode==='demo');openPanel('seed','今天，你想去哪里？','问题是世界的种子。不必先知道答案，选择一个想走的方向。',`
 <form id="seed-form"><label class="field-label" for="seed-input">带上你的问题</label><div class="field-row"><input class="input" id="seed-input" name="seed" placeholder="例如：我们如何在变化中找到自己的方向？" minlength="2" maxlength="100" required autocomplete="off"><button class="btn" type="submit" ${s.session?.features.liveSearch?'':'disabled'}>寻找真实内容 ${icon('arrow',17)}</button></div><p class="help">2–100 个字符 · 自由问题使用知乎搜索${s.session?.features.liveSearch?'，每次创建最多一次检索':'；服务端未配置密钥，暂不可用'}。搜索摘要与正文严格区分。</p></form>
 ${real.length?`<div class="section-title">已有真实来源路线</div><div class="seed-grid">${real.map(p=>seedCard(p)).join('')}</div>`:''}
 <div class="section-title"><span>三条可立即体验的原创路线</span>${button('random-seed','随心出发 ↗','text-btn')}</div><div class="seed-grid">${demo.map(p=>seedCard(p)).join('')}</div><div class="notice warn" style="margin-top:19px">这些路线使用随包原创演示文章，不是知乎 API 的返回结果。无需网络即可完成探索、阅读、收藏和手工洞察。</div>
 <div class="button-row">${button('knowledge-catalog','读取官方知识目录','btn secondary')}${button('journal','继续已有旅程','text-btn')}</div><p class="help">官方知识列表由后端按活动文档读取，不要求 Access Secret；是否可访问取决于实际活动接口。</p>`,{size:'wide'});
 $('#seed-form').onsubmit=e=>{e.preventDefault();if(e.isComposing)return;let text=$('#seed-input').value.trim();if([...text].length<2||[...text].length>100)return toast('问题需要 2–100 个字符。',true);startWorld({seedText:text,seedMode:'search'})}
}
function seedCard(p){return `<button class="seed-card" data-action="preset" data-id="${esc(p.id)}"><span class="seed-number">${p.dataMode==='demo'?'ORIGINAL DEMO':'SOURCE VERIFIED'}</span><h3>${esc(p.seedText)}</h3><small>${esc(p.description||'来自官方活动知识接口')}<br>${date(p.sourceFetchedAt)} · ${p.dataMode==='demo'?'自制演示':'缓存来源'}</small></button>`}
async function catalogPanel(){openPanel('catalog','知乎知识目录','点击后才向官方活动接口发送一次目录请求。缓存有效时不会重复请求。','<div class="progress-detail">正在读取官方目录…</div>');let id=modalId;try{let d=await api.call('/catalog/knowledge');if(id!==modalId)return;openPanel('catalog','知乎知识目录',`实际获取时间：${date(d.sourceFetchedAt)} · ${d.dataMode==='cached'?'缓存':'本次获取'}`,d.items.length?`<div class="seed-grid">${d.items.map(p=>`<button class="seed-card" data-action="knowledge" data-id="${esc(p.id)}"><span class="seed-number">ZHIHU KNOWLEDGE</span><h3>${esc(p.title)}</h3><small>${esc(short(p.description,100))}</small></button>`).join('')}</div>`:empty('暂时没有可用条目','未构造替代内容。'),{size:'wide'})}catch(e){if(id!==modalId)return;openPanel('catalog','知识目录暂不可用','这不是“搜索结果为空”，而是内容服务未能返回有效结果。',`<div class="notice error">${esc(e.message)}</div>${button('seed','返回已有路线','btn')}`,{size:'narrow'})}}
let currentJob=null;
function stages(stage,type){let values=type==='synthesis'?['checking_sources','generating','done']:type==='field'?['structuring','done']:['retrieving','structuring','layout'];let names=type==='synthesis'?['核对来源','整理联系','完成草稿']:type==='field'?['校验正文','准备场域']:['寻找内容','梳理话题','点亮世界'];let idx=values.indexOf(stage);if(idx<0)idx=0;return `<div class="progress">${names.map((n,i)=>`<div class="progress-step ${i===idx?'current':i<idx?'done':''}"><div class="circle">${i<idx?'✓':i+1}</div>${n}</div>`).join('')}</div><div class="progress-detail">${type==='synthesis'?'仅使用你选中的材料；结果保存前仍是草稿。':'正在执行实际任务，不显示虚构进度百分比。'}<br>取消只停止后续进入，不保证撤回已发生的上游调用。</div>`}
async function task(path,body,type='world',show=true){let token=++jobToken;currentJob=null;if(show)openPanel('progress',type==='synthesis'?'让收获产生联系':type==='field'?'走进这篇内容':'为你的问题点亮世界','',stages('queued',type),{size:'narrow',footer:button('cancel-job','取消等待','btn secondary')});let j=await api.call(path,'POST',body,crypto.randomUUID());if(j.fieldId||j.synthesisId)return j;currentJob=j.id||j.jobId;if(token!==jobToken){await api.call('/jobs/'+currentJob+'/cancel','POST',{});throw new Error('任务已取消。')}
 let started=Date.now();for(let i=0;;i++){
  if(token!==jobToken)throw new Error('任务已取消。');if(j.status==='succeeded'){currentJob=null;if(show){s.modal=null;$('#overlay-root').innerHTML=''}return j.result}
  if(j.status==='failed'||j.status==='cancelled'){currentJob=null;throw new ApiError(j.error||{message:'任务已取消。',code:'CANCELLED'},502)}
  if(show&&s.modal==='progress')$('.panel-body').innerHTML=stages(j.stage,type);
  if(Date.now()-started>50000){currentJob=null;throw new Error('等待已结束。任务结果仍保留在服务端，请在日志中检查旅程，不要连续重复创建。')}
  await new Promise(r=>setTimeout(r,i===0?400:i<2?900:1800));if(document.hidden){await new Promise(r=>setTimeout(r,1000));continue}j=await api.call('/jobs/'+(j.id||j.jobId));
 }
}
async function cancelProgress(){jobToken++;let id=currentJob;currentJob=null;s.modal=null;$('#overlay-root').innerHTML='';if(id){try{await api.call('/jobs/'+id+'/cancel','POST',{})}catch{toast('已停止等待；取消请求暂未送达，结果不会自动切换当前页面。')}}render()}
async function startWorld(body){if(s.busy)return;s.busy=true;engine?.pause();try{if(s.journey?.status==='active'){await flushEvents();await saveCheckpoint()}let result=await task('/worlds',body);await loadJourney(result.journeyId);toast('世界已点亮。先靠近前方话题，阅读并收集一份触动你的内容。')}catch(e){if(e.message!=='任务已取消。')errorPanel('起程暂未完成',e,'seed')}finally{s.busy=false}}
function errorPanel(title,e,action='close'){openPanel('error',title,'已保留现有数据，不会用合成内容冒充上游结果。',`<div class="notice error">${esc(e.message)}</div>${button(action,action==='seed'?'返回路线选择':'返回','btn')}`,{size:'narrow'})}
async function contentList(world){
 const ids=[...new Set(world.nodes.flatMap(n=>n.contentIds))];
 return Promise.all(ids.map(id=>api.call('/contents/'+id+'?snapshotId='+encodeURIComponent(world.snapshotMap[id]))));
}
async function loadContents(){const world=s.world,intent=sceneIntent,cs=await contentList(world);if(!currentIntent(intent)||s.world!==world)return;s.contentMap=new Map(cs.map(c=>[c.id,c]));engine?.setContents(cs)}
async function loadJourney(id,takeover=false){
 const intent=beginSceneIntent();let j=await api.call('/journeys/'+id);if(!currentIntent(intent))return;
 if(j.status==='completed')return mapPanel(id);
 if(j.status==='paused'){j=await api.call('/journeys/'+id+'/resume','POST',{expectedVersion:j.version});if(!currentIntent(intent))return}
 try{await api.call('/journeys/'+id+'/lease','POST',{expectedVersion:j.version,takeover})}
 catch(e){if(!currentIntent(intent))return;if(e.code==='TAB_CONFLICT'){s.journey=j;openPanel('lease','旅程正在另一个标签页中','接管后，旧标签页无法再保存移动检查点。',`<div class="notice warn">${esc(e.message)}</div>${button('takeover','在此标签页接管','btn')}`,{size:'narrow'});return}throw e}
 if(!currentIntent(intent))return;
 const world=await api.call('/worlds/'+j.worldId);if(!currentIntent(intent))return;
 const contents=await contentList(world);if(!currentIntent(intent))return;
 let field=null,back=j.checkpoint.returnContext;
 if(j.checkpoint.scene==='field'&&j.checkpoint.fieldId){try{field=await api.call('/fields/'+j.checkpoint.fieldId)}catch{if(currentIntent(intent))toast('场域无法恢复，已安全返回主世界。');back=null}}
 if(!currentIntent(intent))return;
 eventsBuffer=[];s.journey=j;s.world=world;s.contentMap=new Map(contents.map(c=>[c.id,c]));s.readonly=false;s.returnContext=back;s.field=field;
 s.page=field?'field':'world';s.modal=null;$('#overlay-root').innerHTML='';
 if(engine&&await engine.setScene(s.page,world,field,j.checkpoint)===false)return;if(!currentIntent(intent))return;
 engine?.setContents(contents);await refreshPrivate();if(!currentIntent(intent))return;
 await local.put('cache',api.owner+':journey',{journey:j,world,contents,field});if(!currentIntent(intent))return;
 pushRoute('/journeys/'+id+(field?'/field/'+field.id:''));render();
}
function cpNow(){let cp=engine&&!engine.busy&&engine.kind===s.page?engine.checkpoint():s.journey.checkpoint;return {position:cp.position,yaw:cp.yaw||0,camera:cp.camera||{yaw:0,pitch:.22,distance:5},trackedNodeId:cp.trackedNodeId||null,navigationMode:cp.navigationMode||0,worldVersion:s.world.version,scene:s.page==='field'?'field':'world',fieldId:s.field?.id||null,returnContext:s.returnContext||null}}
function saveCheckpoint(override=null){if(!override&&engine&&(engine.busy||engine.kind!==s.page))return Promise.resolve();let target=s.journey?.id;if(!target||s.journey.status!=='active'||s.readonly)return Promise.resolve();saveQueue=saveQueue.catch(()=>{}).then(async()=>{if(s.journey?.id!==target)return;let cp=override||cpNow();await local.put('drafts',api.owner+':checkpoint:'+target,{checkpoint:cp,version:s.journey.version});setSave('正在保存');try{let j=await api.call('/journeys/'+target+'/checkpoint','PUT',{expectedVersion:s.journey.version,checkpoint:cp});if(s.journey?.id===target)s.journey=j;await local.del('drafts',api.owner+':checkpoint:'+target);setSave('已保存到本机服务')}catch(e){setSave('检查点待保存');if(e.status===409){s.readonly=true;engine?.pause();toast(e.message+' 请从日志重新载入或接管。',true)}throw e}});return saveQueue}
function queueEvent(type,topicId,payload={},worldNodeId=null){if(!s.journey||s.journey.status!=='active'||s.readonly)return;let e={eventId:crypto.randomUUID(),type,topicId:topicId||null,worldNodeId,occurredAt:new Date().toISOString(),payload:{scene:s.page==='field'?'field':'world',...payload}};eventsBuffer.push(e);local.put('drafts',api.owner+':events:'+s.journey.id,{journeyId:s.journey.id,events:eventsBuffer}).catch(()=>{})}
async function flushEvents(){if(flushing||!s.journey||!eventsBuffer.length||s.readonly)return;flushing=true;let id=s.journey.id,batch=eventsBuffer.slice(0,50);try{let d=await api.call('/journeys/'+id+'/events','POST',{events:batch});let acknowledged=new Set(d.accepted.map(x=>x.eventId));eventsBuffer=eventsBuffer.filter(x=>!acknowledged.has(x.eventId));await local.put('drafts',api.owner+':events:'+id,{journeyId:id,events:eventsBuffer})}catch(e){if(e instanceof ApiError&&e.status===409){s.readonly=true;engine?.pause();toast(e.message,true)}}finally{flushing=false}}
async function expandNode(n,automatic=false){
 if(expanding||s.readonly||s.page!=='world')return;
 if(n.expansionState==='expanded'||n.expansionState==='exhausted')return toast('这条分支已展开，重复访问不会增加调用。');
 expanding=true;const intent=sceneIntent,worldId=s.world.worldId;
 try{
  const result=await task('/worlds/'+worldId+'/expansions',{nodeId:n.id,expectedVersion:s.world.version},'expand',!automatic);
  if(!currentIntent(intent)||s.world?.worldId!==worldId)return;
  const world=await api.call('/worlds/'+worldId),contents=await contentList(world);
  if(!currentIntent(intent)||s.world?.worldId!==worldId)return;
  if(engine&&!await engine.updateWorld(world))return;
  if(!currentIntent(intent))return;
  s.world=world;s.contentMap=new Map(contents.map(c=>[c.id,c]));engine?.setContents(contents);
  if(contextNode)contextNode=world.nodes.find(node=>node.id===contextNode.id)||null;
  // Background expansion never replaces DOM, unlocks the mouse, or resets the camera.
  if(!automatic)render();else{updateNav();if(engine?.target)onTarget(engine.target,dist(engine.player,engine.target.position))}
  if(result.newNodes?.length)toast(`新的小径已出现：${result.newNodes.length} 个话题。继续漫游即可。`);
  else if(!automatic)toast('这条分支暂时没有更多新内容。');
  await saveCheckpoint();
 }catch(e){if(!automatic&&e.message!=='任务已取消。')errorPanel('扩展暂未完成',e);else toast('扩展暂不可用，原场景仍可继续漫游。',true)}
 finally{expanding=false}
}

async function topicPanel(id){let n=s.page==='field'?s.field.sections.find(n=>n.id===id):s.world.nodes.find(n=>n.id===id);if(!n)return;if(s.page==='field'){let actual=s.world.nodes.find(x=>x.contentIds.includes(s.field.contentId));contextNode=actual;return readContent(s.field.contentId,n.excerptId)}contextNode=n;let contents=n.contentIds.map(id=>s.contentMap.get(id)).filter(Boolean);openPanel('topic',n.title,'你选择的下一站。先阅读来源，再决定是否把它带走。',`<div class="notice">${esc(s.world.semanticMethod)}</div><div class="topic-detail">${contents.map(c=>`<div><div class="source-line">${modeBadge(c.dataMode,true)}<span>${esc(c.authorName)}</span></div><h3>${esc(c.title)}</h3><p class="quote">${esc(c.excerpts[0]?.text||'暂无摘录')}</p><p class="help">${c.coverage==='summary'?'搜索摘要片段':'原文摘录'} · ${date(c.sourceFetchedAt)}</p><div class="button-row">${button('read-content','打开阅读器','btn',`data-id="${c.id}"`)}${button('collect-content','收集内容','btn secondary',`data-id="${c.id}"`)}</div></div>`).join('')}</div>`,{footer:`<small>${n.expansionState==='expanded'?'分支已展开':n.expansionState==='exhausted'?'暂时没有更多新材料':'扩展至多触发一次新的上游查询'}</small><div class="button-row">${button('anchor','留下想法','btn small secondary')}${button('track-node','沿路追踪','btn small secondary',`data-id="${n.id}"`)}${button('expand-node','展开新方向','btn small',`data-id="${n.id}" ${['expanded','exhausted'].includes(n.expansionState)?'disabled':''}`)}</div>`})}
async function readContent(id,excerptId=null){let c=s.contentMap.get(id)||await api.call('/contents/'+id);activeContent=c;if(!contextNode)contextNode=s.world?.nodes.find(n=>n.contentIds.includes(id))||null;queueEvent('content_opened',contextNode?.topicId);openPanel('reader',c.title,`${c.authorName} · ${c.sourceLabel}`,`
 <div class="source-line">${modeBadge(c.dataMode,true)}<span>${c.coverage==='summary'?'仅搜索摘要':c.coverage==='chapter'?'已获取章节正文':'已获取正文'}</span><span>${date(c.sourceFetchedAt)}</span></div>
 ${c.coverage==='summary'?'<div class="notice warn">以下是搜索接口的摘要，不是文章全文。全文场域不可用，请通过原链接阅读。</div>':''}
 ${c.workId?`<div class="notice">活动内容 work_id：${esc(c.workId)}${c.chapterName?'<br>章节：'+esc(c.chapterName):''}。接口未给出原链接时，不自行拼造知乎 URL。</div>`:''}
 ${c.paragraphs.map(p=>{let e=c.excerpts.find(e=>e.paragraphIds.includes(p.id));return `<p class="article-paragraph ${e?.id===excerptId?'focus-paragraph':''}"><span class="para-id">${esc(p.id)}</span>${esc(p.text)}${e?button('collect-excerpt','＋ 收集片段','collect-para',`data-id="${e.id}" data-content="${c.id}"`):''}</p>`}).join('')}
 <div class="source-footer">获取范围：${esc(c.coverage)}<br>来源快照：${esc(c.snapshotId)}<br>${c.dataMode==='demo'?'这是随包自制演示文章，不是知乎内容。':'外部观点属于原作者；导览不代表独立事实核验。'}${c.sourceUrl?`<br><a href="${esc(c.sourceUrl)}" target="_blank" rel="noopener noreferrer">在原始来源继续阅读 ↗</a>`:''}</div>`,{reader:true,footer:`<small>${c.canEnterField?'正文具备规则结构导览条件':esc(c.fieldDisabledReason)}</small><div class="button-row">${button('collect-content','E 收集内容','btn small secondary',`data-id="${c.id}"`)}${button('enter-field',s.page==='field'?'已在文章场域':'F 进入文章场域','btn small',`data-id="${c.id}" ${!c.canEnterField||s.page==='field'||!s.journey?'disabled':''}`)}</div>`})}
async function collect(type,id){if(type==='content'&&!s.contentMap.has(id)){let c=await api.call('/contents/'+id);s.contentMap.set(id,c)}let old=s.bag.find(x=>x.targetType===type&&x.targetId===id);if(old)return toast('已经在你的行囊中。');setSave('正在收录');let d=await api.mutate('/bag/items','POST',{targetType:type,targetId:id,journeyId:s.journey?.id||null});if(d.pending){s.pending++;setSave('离线 · 收录待同步');toast('已放入本机待同步队列，尚未确认保存。');return}await refreshPrivate();sound();toast(d.alreadyCollected?'已在行囊中。':'已收录到知识行囊。回家后，也会出现在想法收纳柜中。');if(!s.modal)render()}
async function enterField(cid){
 if(!s.journey||s.page==='field')return;const c=s.contentMap.get(cid);if(!c?.canEnterField)return toast(c?.fieldDisabledReason||'当前内容不具备正文结构。');
 const back=engine?engine.checkpoint():s.journey.checkpoint;
 const returnContext={position:back.position,yaw:back.yaw||0,camera:back.camera,trackedNodeId:back.trackedNodeId||null,navigationMode:back.navigationMode||0};
 const intent=beginSceneIntent();
 try{
  const result=await task('/contents/'+cid+'/fields',{snapshotId:c.snapshotId,templateType:'argument'},'field');if(!currentIntent(intent))return;
  const f=await api.call('/fields/'+result.fieldId);if(!currentIntent(intent))return;
  const cp={...returnContext,position:f.spawn.position,worldVersion:s.world.version,scene:'field',fieldId:f.id,returnContext};
  await saveCheckpoint(cp);if(!currentIntent(intent))return;
  s.returnContext=returnContext;s.field=f;s.page='field';s.modal=null;$('#overlay-root').innerHTML='';
  if(engine&&await engine.setScene('field',s.world,f,cp)===false)return;if(!currentIntent(intent))return;
  engine?.setContents([...s.contentMap.values()]);pushRoute('/journeys/'+s.journey.id+'/field/'+f.id);render();queueEvent('field_entered',contextNode?.topicId);toast('已进入正文场域。每个节点都对应实际段落，可随时返回原位置。');
 }catch(e){if(currentIntent(intent)&&e.message!=='任务已取消。')errorPanel('场域准备未完成',e)}
}
async function returnWorld(){
 if(!s.field)return;const intent=beginSceneIntent();
 try{
  const back=s.returnContext||{position:s.world.spawn.position,yaw:0,camera:{yaw:0,pitch:.22,distance:5}};
  queueEvent('field_exited',contextNode?.topicId);await flushEvents();if(!currentIntent(intent))return;
  const cp={...back,worldVersion:s.world.version,scene:'world',fieldId:null,returnContext:null};await saveCheckpoint(cp);if(!currentIntent(intent))return;
  s.field=null;s.returnContext=null;s.page='world';closePanel();
  if(engine&&await engine.setScene('world',s.world,null,cp)===false)return;if(!currentIntent(intent))return;
  engine?.setContents([...s.contentMap.values()]);render();pushRoute('/journeys/'+s.journey.id);toast('已回到进入场域前的位置。');
 }catch(e){if(currentIntent(intent))errorPanel('返回检查点未保存',e)}
}
async function bagPanel(filter='all',q=''){await refreshPrivate();let selected=s.selected;for(let id of selected)if(!s.bag.some(b=>b.id===id))selected.delete(id);let tags=[...new Set(s.bag.flatMap(b=>b.tags||[]))];let display=s.bag.filter(b=>(filter==='all'||filter==='current'&&b.journeyId===s.journey?.id||b.tags?.includes(filter))&&(!q||(b.title+b.text+b.note+(b.tags||[]).join(' ')).toLowerCase().includes(q.toLowerCase())));
 openPanel('bag',s.page==='home'?'想法收纳柜':'知识行囊','行囊和收纳柜是同一份收藏库。按下 E 带回的内容，在这里继续生长。',`
 <div class="tabs">${['all',...(s.journey?['current']:[]),...tags].map(t=>button('bag-filter',t==='all'?'全部收获':t==='current'?'本次收获':esc(t),'tab '+(filter===t?'active':''),`data-id="${esc(t)}"`)).join('')}</div>
 <form id="bag-search"><div class="field-row"><input class="input" id="bag-query" aria-label="搜索收藏" placeholder="搜索内容、标签或自己的备注…" value="${esc(q)}"><button class="btn secondary" type="submit">搜索</button></div></form><div class="divider"></div>
 <div class="bag-layout"><div class="bag-list">${display.length?display.map(b=>`<article class="bag-card ${selected.has(b.id)?'selected':''}"><input type="checkbox" class="check" data-bag="${b.id}" aria-label="选中：${esc(b.title)}" ${selected.has(b.id)?'checked':''}><div class="source-line" style="margin:0">${modeBadge(b.dataMode,true)}<span>${esc(kindLabel(b.kind))}</span></div><h3>${esc(b.title)}</h3><p class="quote">${esc(short(b.text,140)||'话题收藏需要对应正文或摘录，才能用于合成。')}</p><div class="tags">${(b.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>${b.note?`<p class="help" style="margin:10px 0 0">我的备注：${esc(short(b.note,100))}</p>`:''}<div class="card-actions">${button('bag-source','查看来源','mini-btn',`data-id="${b.id}"`)}${button('bag-edit','备注 / 标签','mini-btn',`data-id="${b.id}"`)}${button('bag-remove','移除','mini-btn',`data-id="${b.id}"`)}<span class="help" style="margin:0 0 0 auto">${date(b.createdAt)}</span></div></article>`).join(''):empty('先带回一束微光','走近话题，打开阅读器，收集让你停留的片段。')}</div><aside class="bag-aside"><div class="eyebrow">CONNECT THE DOTS</div><h3>不止收藏，<br>试着建立联系。</h3><p class="help">选择 2–4 份内容或摘录。来源会一起进入合成台，不会只剩两个词。</p><div class="selected-list" id="selected-list"></div>${button('selected-synthesis','送往合成台','btn')}${button('link-materials','建立手工连线','btn secondary')}${button('links-panel','查看已建连线','text-btn')}<p class="help">手工连线需要恰好两份材料；重复连线不会产生第二条关系。</p></aside></div>`,{size:'wide'});
 $('#bag-search').onsubmit=e=>{e.preventDefault();bagPanel(filter,$('#bag-query').value)};$$('[data-bag]').forEach(c=>c.onchange=()=>{if(c.checked){if(s.selected.size>=4){c.checked=false;return toast('一次最多选择四份材料。')}s.selected.add(c.dataset.bag)}else s.selected.delete(c.dataset.bag);c.closest('.bag-card').classList.toggle('selected',c.checked);renderSelected()});renderSelected()
}
function kindLabel(kind){return ({summary:'搜索摘要',full_text:'正文',chapter:'章节正文',original_excerpt:'原文摘录',search_summary:'摘要片段',topic:'话题词',user_insight:'个人洞察',ai_insight:'AI 辅助洞察'})[kind]||kind}
function renderSelected(){let el=$('#selected-list');if(el)el.innerHTML=s.selected.size?[...s.selected].map((id,i)=>`<p style="margin-bottom:10px">${i+1}. ${esc(s.bag.find(b=>b.id===id)?.title)}</p>`).join(''):'尚未选择材料';$('#overlay-root [data-action="selected-synthesis"]')?.toggleAttribute('disabled',s.selected.size<2);$('#overlay-root [data-action="link-materials"]')?.toggleAttribute('disabled',s.selected.size!==2)}
async function editBag(id){let b=s.bag.find(x=>x.id===id);openPanel('bag-edit','为这份收获做个标记',b.title,`<form id="bag-edit-form"><div class="form-group"><label for="bag-tags" class="field-label">主题标签，用逗号分隔</label><input id="bag-tags" class="input" value="${esc((b.tags||[]).join('，'))}" maxlength="300"></div><div class="form-group"><label for="bag-note" class="field-label">自己的备注</label><textarea id="bag-note" maxlength="1000">${esc(b.note)}</textarea></div><div class="notice">手工标签优先保存，不会被后续自动归类覆盖。</div><button class="btn" type="submit">保存修改</button></form>`,{size:'narrow'});$('#bag-edit-form').onsubmit=async e=>{e.preventDefault();try{let d=await api.mutate('/bag/items/'+id,'PATCH',{expectedVersion:b.version,tags:$('#bag-tags').value.split(/[,，]/).map(t=>t.trim()).filter(Boolean),note:$('#bag-note').value});if(d.pending){toast('修改已保留为待同步，当前成功版本未改变。');closePanel()}else{toast('备注与标签已保存。');await bagPanel()}}catch(e){toast(e.message,true)}}}
async function linksPanel(){let links=(await api.call('/bag/links')).items;openPanel('links','收获之间的小径','连线由你建立，不代表系统已经证明了材料间的因果关系。',links.length?links.map(l=>`<div class="anchor-card"><div class="context">手工联系</div><h3>${esc(s.bag.find(b=>b.id===l.sourceBagItemId)?.title||'材料')} ↔ ${esc(s.bag.find(b=>b.id===l.targetBagItemId)?.title||'材料')}</h3><p>${esc(l.note||'未填写联系说明')}</p>${button('remove-link','删除这条联系','mini-btn',`data-id="${l.id}"`)}</div>`).join(''):empty('这里还没有连线','从行囊选择两份材料，写下你看见的联系。'))}
async function linkMaterials(){if(s.selected.size!==2)return toast('需要恰好两份材料。');openPanel('link','这两份收获，如何相连？','连线会保存在个人知识库，不自动发布。',`<form id="link-form"><label for="link-note" class="field-label">联系说明（可选）</label><textarea id="link-note" maxlength="500" placeholder="它们共享一个问题，还是恰好呈现了不同的选择？"></textarea><div class="button-row" style="margin-top:20px"><button class="btn" type="submit">保存连线</button></div></form>`,{size:'narrow'});$('#link-form').onsubmit=async e=>{e.preventDefault();try{let [a,b]=[...s.selected],d=await api.mutate('/bag/links','POST',{sourceBagItemId:a,targetBagItemId:b,note:$('#link-note').value});toast(d.pending?'连线待同步，尚未确认。':'连线已保存。');closePanel()}catch(e){toast(e.message,true)}}}
function getContext(){if(contextNode&&s.world?.nodes.some(n=>n.id===contextNode.id))return contextNode;if(s.page==='field')return s.world?.nodes.find(n=>n.contentIds.includes(s.field.contentId));let n=engine?.nearest();return n&&dist(engine.player,n.position)<12?n:null}
async function anchorEditor(id=null){let old=id?s.anchors.find(a=>a.id===id):null,n=old?s.world?.nodes.find(n=>n.topicId===old.topicId):getContext();if(!old&&(!s.journey||!n))return toast('先靠近一个话题，或在简化模式中打开话题，再留下想法。');let draftId=api.owner+':anchor:'+(id||s.journey.id+':'+n.topicId),draft=await local.get('drafts',draftId);openPanel('anchor',old?'回到当时的想法':'在这里，留下一个想法',`绑定语境：${old?.topicTitle||n.title} · 仅自己可见`, `<form id="anchor-form"><label class="field-label" for="anchor-text">想法不是标准答案。把此刻的你留在这里。</label><textarea id="anchor-text" rows="7" maxlength="500" required placeholder="这一刻，我想到…">${esc(draft?.value?.text??old?.text??'')}</textarea><p class="help"><span id="anchor-count">0</span> / 500 · 本机自动保留草稿。私人锚点不会发布到知乎。</p><div class="button-row"><button class="btn" type="submit">${old?'保存修改':'种下想法锚点'}</button>${button('anchors','查看已有想法','text-btn')}</div><div id="anchor-error"></div></form>`,{size:'narrow'});
 let text=$('#anchor-text'),update=()=>{$('#anchor-count').textContent=[...text.value].length;local.put('drafts',draftId,{text:text.value}).catch(()=>{})};text.oninput=update;update();$('#anchor-form').onsubmit=async e=>{e.preventDefault();let body=old?{text:text.value.trim(),expectedVersion:old.version,visibility:'private'}:{journeyId:s.journey.id,topicId:n.topicId,contentId:n.contentIds[0],text:text.value.trim(),visibility:'private',localOffset:{x:2,y:0,z:3}};try{let d=await api.mutate('/anchors'+(old?'/'+old.id:''),old?'PATCH':'POST',body);if(d.pending){toast('想法已保存在本机待同步队列，尚未确认服务器保存。');setSave('锚点待同步')}else{await local.del('drafts',draftId);await refreshPrivate();toast('想法已保存，只属于你。')}closePanel()}catch(e){$('#anchor-error').innerHTML=`<div class="notice error" style="margin-top:18px">${esc(e.message)} 草稿仍在本机。${e.status===409?'请关闭编辑器后重新打开，比较最新记录。':''}</div>`}}
}
async function anchorsPanel(scope='all'){try{s.anchors=(await api.call('/anchors')).items}catch(e){if(e instanceof ApiError)throw e;toast('离线：显示已加载的私人锚点。')};let n=getContext(),items=scope==='context'&&n?s.anchors.filter(a=>a.topicId===n.topicId):s.anchors;openPanel('anchors','那些停留过的念头','私人想法锚点。可以修订，也可以收回。',items.length?items.map(a=>`<div class="anchor-card"><div class="context">${esc(a.topicTitle)} · 仅自己可见 · ${date(a.updatedAt)}</div><p>${esc(a.text)}</p><div class="button-row">${button('edit-anchor','编辑','mini-btn',`data-id="${a.id}"`)}${button('remove-anchor','删除','mini-btn',`data-id="${a.id}"`)}</div></div>`).join(''):empty('一段路，也可以留下一个问题','靠近话题按 R，记下你的思考。'))}
async function synthesisPanel(){await refreshPrivate();let materials=[...s.selected].map(id=>s.bag.find(b=>b.id===id)).filter(Boolean);if(materials.length<2)return openPanel('synthesis','思维合成台','把不同地方带回的微光，放在同一张桌上。',empty('带回两份收获，再来试试','从知识行囊选中 2–4 份正文或摘录。话题词本身不是证据。')+`<div class="button-row" style="justify-content:center">${button('bag','打开知识行囊','btn')}</div>`,{size:'narrow'});
 if(materials.some(m=>m.targetType==='topic'||!m.text))return toast('请移除没有正文或摘录的话题词，再选择有效证据。',true);
 openPanel('synthesis','在不同的收获之间','先看清材料来自哪里，再决定想建立什么联系。',`<div class="synthesis-materials">${materials.map(materialCard).join('')}</div><div class="divider"></div><form id="synthesis-form"><label class="field-label" for="synthesis-question">你想借这组材料理解什么？（可选）</label><textarea id="synthesis-question" rows="3" maxlength="200" placeholder="它们之间共同的问题是什么？哪些差异值得保留？"></textarea><div class="form-group" style="margin-top:18px"><label class="field-label" for="synthesis-mode">创作方式</label><select id="synthesis-mode"><option value="manual">手工建立洞察 · 不调用模型</option><option value="ai" ${s.session?.features.aiSynthesis?'':'disabled'}>知乎直答 AI 辅助 · 需要可用服务端密钥</option></select></div><div class="notice">手工模式只整理材料，不会把固定文字冒充实时 AI。AI 模式仅在收到通过证据校验的有效结果后展示；保存前可编辑。</div><button class="btn" type="submit">准备洞察草稿 ${icon('arrow',17)}</button></form>`,{size:'wide'});
 $('#synthesis-form').onsubmit=async e=>{e.preventDefault();let body={bagItemIds:materials.map(m=>m.id),question:$('#synthesis-question').value,mode:$('#synthesis-mode').value};try{let d=await task('/syntheses',body,'synthesis');await insightEditor(d.synthesisId)}catch(e){if(e.message!=='任务已取消。')openPanel('synthesis-failed','洞察草稿未完成','你的材料组合仍保留，可改为手工写下联系。',`<div class="notice error">${esc(e.message)}</div>${button('synthesis','回到选材','btn')}`,{size:'narrow'})}}
}
function materialCard(m){return `<article class="material"><small>${esc(kindLabel(m.kind))} · ${esc(m.sourceLabel)} · ${m.dataMode==='demo'?'演示':'真实来源'}</small><strong>${esc(m.title)}</strong><p>${esc(short(m.text,320))}</p><small>${esc(m.authorName)}${m.sourceUrl?` · <a href="${esc(m.sourceUrl)}" target="_blank" rel="noopener noreferrer">原始来源 ↗</a>`:''}</small></article>`}
async function insightEditor(id){let d=await api.call('/syntheses/'+id),r=d.result;if(d.status==='saved')return insightView(id);let draftId=api.owner+':insight:'+id,localDraft=await local.get('drafts',draftId);if(localDraft?.value)r={...r,...localDraft.value};openPanel('insight-editor',d.generator==='user'?'写下你看见的联系':'AI 洞察草稿 · 请核对与编辑',d.generator==='user'?'手工创作，不含伪装的 AI 输出。':'AI 输出并非原作者观点。请核对来源和适用条件。',`<form id="insight-form"><div class="form-grid"><div class="form-group full"><label class="field-label" for="insight-title">标题</label><input id="insight-title" class="input" name="title" maxlength="100" required value="${esc(r.title)}"></div><div class="form-group full"><label class="field-label" for="insight-core">核心洞察</label><textarea id="insight-core" name="coreInsight" maxlength="2000" required rows="4" placeholder="结合材料，写下你自己的理解…">${esc(r.coreInsight)}</textarea></div><div class="form-group"><label class="field-label" for="insight-connection">联系如何成立？</label><textarea id="insight-connection" name="connection" maxlength="2000">${esc(r.connection)}</textarea></div><div class="form-group"><label class="field-label" for="insight-uncertainty">差异与不确定性</label><textarea id="insight-uncertainty" name="uncertainty" maxlength="1000">${esc(r.uncertainty)}</textarea></div><div class="form-group full"><label class="field-label" for="insight-questions">接下来想探索的问题（最多三行）</label><textarea id="insight-questions" name="questions" rows="2" maxlength="600">${esc((r.questions||[]).join('\n'))}</textarea></div></div><div class="section-title">本次实际使用的材料</div><div class="synthesis-materials">${d.materials.map(materialCard).join('')}</div><div class="button-row" style="margin-top:24px"><button class="btn" type="submit">保存洞察，带回家园</button></div><p class="help">结果保存后，进入日志和同一份收藏库。来源引用随结果一起保留。</p></form>`,{size:'wide'});
 let form=$('#insight-form');const value=()=>({title:form.elements.title.value,coreInsight:form.elements.coreInsight.value,connection:form.elements.connection.value,uncertainty:form.elements.uncertainty.value,questions:form.elements.questions.value.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,3),personalNote:''});form.oninput=()=>local.put('drafts',draftId,value()).catch(()=>{});form.onsubmit=async e=>{e.preventDefault();try{let result=await api.mutate('/syntheses/'+id+'/save','POST',value());if(result.pending){toast('洞察已在本机待同步，尚未确认保存。');closePanel()}else{await local.del('drafts',draftId);await refreshPrivate();sound();toast('洞察已保存。旅途中的微光，有了新的联系。');await insightView(id)}}catch(e){toast(e.message,true)}}
}
async function insightView(id){let d=await api.call('/insights/'+id),r=d.result;openPanel('insight-view',r.title,`${d.generator==='user'?'个人手工洞察':'AI 辅助洞察，用户已核对保存'} · ${date(d.savedAt||d.createdAt)}`,`<p class="callout-quote">${esc(r.coreInsight)}</p>${r.connection?`<div class="section-title">联系说明</div><p>${esc(r.connection)}</p>`:''}${r.uncertainty?`<div class="notice">差异与不确定性：${esc(r.uncertainty)}</div>`:''}${r.questions?.length?`<div class="section-title">下一段旅程的问题</div>${r.questions.map(q=>`<p>${esc(q)}</p>`).join('')}`:''}<div class="section-title">沿着来源，回到证据</div><div class="synthesis-materials">${d.materials.map(materialCard).join('')}</div>`,{size:'wide',footer:`<small>源材料属于原作者，洞察属于你的个人记录。</small>${button('delete-insight','删除这份洞察','btn small secondary',`data-id="${id}"`)}`})}
async function journalPanel(tab='journeys'){let [js,insights]=await Promise.all([fetchAll('/journeys'),api.call('/insights')]);openPanel('journal','漫行者日志','一条小径，一次停留。你走过的路，都有迹可循。',`<div class="tabs">${button('journal','探索旅程','tab '+(tab==='journeys'?'active':''))}${button('insights-tab','保存的洞察','tab '+(tab==='insights'?'active':''))}${button('anchors','私人锚点','tab')}${button('outbox','待同步与草稿','tab')}</div>${tab==='journeys'?(js.length?js.map((j,i)=>`<article class="journal-card"><div class="number">${String(js.length-i).padStart(2,'0')}</div><div><h3>${esc(j.seedText)}</h3><p>${date(j.startedAt)} · ${j.status==='active'?'进行中':j.status==='paused'?'已暂停':'已归档'} · ${j.stats.topics} 个已访问话题 · ${j.stats.collections} 次收获 · ${j.stats.anchors} 个锚点</p><div style="margin-top:8px">${modeBadge(j.dataMode,true)}</div></div><div class="actions">${j.status!=='completed'?button('resume-journey','继续','btn small',`data-id="${j.id}"`):''}${button('journey-map','星图','btn small secondary',`data-id="${j.id}"`)}${button('remove-journey','删除','mini-btn',`data-id="${j.id}"`)}</div></article>`).join(''):empty('你的第一条小径，尚未开始','回到小屋，推开大门，让一个问题成为起点。')):(insights.items.length?insights.items.map(d=>`<article class="anchor-card"><div class="context">${d.generator==='user'?'手工洞察':'AI 辅助洞察'} · ${date(d.savedAt||d.createdAt)}</div><h3>${esc(d.result.title)}</h3><p>${esc(short(d.result.coreInsight,140))}</p>${button('insight-view','打开洞察','btn small secondary',`data-id="${d.id}"`)}</article>`).join(''):empty('收获之间，还可以有新的联系','选择至少两份材料，带到思维合成台。'))}`,{size:'wide'})}
function mapSvg(nodes,edges,highlight=null){if(!nodes.length)return '';let xmin=Math.min(...nodes.map(n=>n.position.x))-15,xmax=Math.max(...nodes.map(n=>n.position.x))+15,zmin=Math.min(...nodes.map(n=>n.position.z))-15,zmax=Math.max(...nodes.map(n=>n.position.z))+15,scale=Math.min(600/(xmax-xmin),300/(zmax-zmin)),p=n=>[50+(n.position.x-xmin)*scale,30+(n.position.z-zmin)*scale];let colors=['#bdd6a0','#dcc086','#89bdad','#b9b2a0'];return `<svg viewBox="0 0 700 370" role="img" aria-label="按实际话题访问绘制的私人星图">${edges.map(e=>{let a=nodes.find(n=>n.topicId===e.topics?.[0]||n.id===e.source),b=nodes.find(n=>n.topicId===e.topics?.[1]||n.id===e.target);if(!a||!b)return '';let [x1,y1]=p(a),[x2,y2]=p(b);return `<path d="M${x1} ${y1}L${x2} ${y2}" stroke="#b3c092" stroke-width="${1+Math.min(4,e.count||0)}" stroke-opacity="${e.count?.length?'.8':'.35'}" fill="none"/>`}).join('')}${nodes.map((n,i)=>{let [x,y]=p(n),r=6+Math.min(n.visits||0,5)*1.7,active=highlight===n.topicId,opacity=(n.visits||active)?.65+Math.min(n.dwellSeconds||0,600)/600*.35:.38;return `<g class="map-node" tabindex="0" role="button" aria-label="${esc(n.title)}" data-map-node="${n.id}"><circle cx="${x}" cy="${y}" r="${r+8}" fill="${colors[i%4]}" fill-opacity="${active?.35:.08}"/><circle cx="${x}" cy="${y}" r="${r}" fill="${colors[i%4]}" opacity="${opacity}" stroke="${active?'#fff4cd':'#b3cd9d'}" stroke-width="${active?2:.5}"/><text x="${x}" y="${y+25}" text-anchor="middle" fill="#e3e9d5" font-size="11" font-family="serif">${esc(n.title)}</text></g>`}).join('')}</svg>`}
async function mapPanel(jid=s.journey?.id){if(!jid)return journalPanel();await flushEvents();let data=await api.call('/journeys/'+jid+'/canvas'),nodes=data.nodes,edges=data.edges.length?data.edges:s.world?.edges||[],steps=data.steps.filter(x=>x.type==='topic_entered');openPanel('canvas','我的旅途星图',data.journey.seedText,`<div class="map-container"><div class="map-wrap" id="map-wrap">${mapSvg(nodes,edges)}<div class="map-legend">色彩：区域类别 · 大小：访问次数 · 亮度：有效停留（最多 600 秒）<br>线宽：往返次数 · 灰暗节点：已生成，尚未访问 · 连线不是事实推断</div></div><aside class="map-info" id="map-info"><div class="eyebrow">YOUR OWN TRAIL</div><h3>一路走来，<br>你留下了什么？</h3><p>${data.journey.stats.topics} 个实际访问话题<br>${data.bag.length} 份仍保留的收获<br>${data.anchors.length} 个私人想法</p><p>点击一个节点，回到它关联的内容。这里记录的是语义访问，不是逐帧动作录像。</p></aside></div><label class="slider-label" for="map-time">访问时间线<input type="range" id="map-time" min="0" max="${steps.length}" value="0"><span id="map-time-label">全部</span></label>`,{size:'wide',footer:`<small>${modeBadge(data.journey.dataMode,true)} · ${date(data.journey.startedAt)}</small><div class="button-row">${data.journey.status!=='completed'?button('resume-journey','回到这段旅程','btn small',`data-id="${jid}"`):''}${button('journal','回到日志','btn small secondary')}</div>`});
 function bind(){ $$('[data-map-node]').forEach(el=>{let view=()=>{let n=nodes.find(n=>n.id===el.dataset.mapNode),bag=data.bag.filter(b=>b.topicId===n.topicId),anchors=data.anchors.filter(a=>a.topicId===n.topicId);$('#map-info').innerHTML=`<div class="eyebrow">${esc(n.biome)}</div><h3>${esc(n.title)}</h3><p>访问 ${n.visits} 次 · 有效停留 ${Math.round(n.dwellSeconds)} 秒<br>${bag.length} 份收获 · ${anchors.length} 个想法</p>${bag.map(b=>`<p>✧ ${esc(b.title)}</p>`).join('')}${anchors.map(a=>`<p>「${esc(short(a.text,90))}」</p>`).join('')}${s.journey?.id===jid&&s.page==='world'?button('topic','打开这个话题','btn small secondary',`data-id="${n.id}"`):''}`};el.onclick=view;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();view()}}})}bind();$('#map-time').oninput=()=>{let step=steps[Number($('#map-time').value)-1];$('#map-time-label').textContent=step?`${step.seq} · ${date(step.occurredAt)}`:'全部';let legend=$('.map-legend').outerHTML;$('#map-wrap').innerHTML=mapSvg(nodes,edges,step?.topicId)+legend;bind()}
}
function pausePanel(){engine?.pause();if(!s.journey)return home({skipPause:true});openPanel('pause','让脚步休息一下','保存并回家后，可以继续这段旅程；归档后，历史只读。',`<div class="notice">${esc(s.world.seedText)}<br>已确认的收藏和锚点不会因退出漫游而丢失。</div><div class="button-row">${button('pause-home','保存并回家','btn')}${button('archive','结束并归档','btn secondary')}${button('close','留在这里','text-btn')}</div>${s.readonly?`<div class="notice warn" style="margin-top:20px">当前标签页没有写入控制权。${button('takeover','重新载入 / 显式接管','text-btn')}</div>`:''}`,{size:'narrow'})}
async function pauseJourney(){try{engine?.pause();await flushEvents();await saveCheckpoint();let cp=cpNow(),j=await api.call('/journeys/'+s.journey.id+'/pause','POST',{expectedVersion:s.journey.version,checkpoint:cp});s.journey=j;await home({skipPause:true});toast('旅程已保存。欢迎回家。')}catch(e){openPanel('save-failed','暂时未确认保存','本机检查点草稿已保留，不会显示“云端已保存”。',`<div class="notice error">${esc(e.message)}</div><div class="button-row">${button('pause-home','重试保存','btn')}${button('local-home','保留本机草稿后回家','btn secondary')}</div>`,{size:'narrow'})}}
async function archiveJourney(){if(!await confirmDialog('结束并归档这段旅程？','已确认收藏与锚点保留；这段探索的事件与检查点不再修改。','归档旅程'))return;try{await flushEvents();await saveCheckpoint();let id=s.journey.id;s.journey=await api.call('/journeys/'+id+'/complete','POST',{expectedVersion:s.journey.version});await home({skipPause:true});await mapPanel(id)}catch(e){toast(e.message,true)}}
async function confirmDialog(title,description,label='确认'){return new Promise(resolve=>{openPanel('confirm',title,description,`<div class="button-row"><button class="btn danger" id="confirm-yes">${esc(label)}</button><button class="btn secondary" id="confirm-no">取消</button></div>`,{size:'narrow'});$('#confirm-yes').onclick=()=>{closePanel();resolve(true)};$('#confirm-no').onclick=()=>{closePanel();resolve(false)};$('#overlay-root [data-action="close"]').onclick=e=>{e.stopPropagation();closePanel();resolve(false)}})}
function phonePanel(){openPanel('phone','同频电话亭','有一天，你会遇见沿着相似问题走来的旅人。',`<div class="empty"><div class="phone-illustration" aria-hidden="true"></div><h3 style="margin-top:25px">电话还没有响起。</h3><p>同频匹配、公开锚点与聊天尚未开放。<br>这里没有虚构的在线人数，也没有随机生成的匹配率。</p><div class="notice">你的旅程、想法与收藏默认私人。未来仅在你主动公开且允许匹配后，才会使用公开轨迹寻找同路人。</div>${button('journal','先看看自己的旅途','btn secondary')}</div>`,{size:'narrow'})}
function settingsPanel(){openPanel('settings','把漫游调成你的节奏','设置保存在当前浏览器；关闭面板后生效。',`

 <div class="settings-row"><label for="setting-quality">画质<small>主要调整渲染像素比；不影响内容与存档。</small></label><select id="setting-quality">${['low','medium','high'].map((x,i)=>`<option value="${x}" ${s.settings.quality===x?'selected':''}>${['低','中','高'][i]}</option>`).join('')}</select></div>
 <div class="settings-row"><label for="setting-auto">自动降低画质</label><input id="setting-auto" type="checkbox" ${s.settings.autoQuality?'checked':''}></div>
 <div class="settings-row"><label for="setting-motion">减少动态效果<small>关闭角色呼吸摆动；导航改为静态分段线。</small></label><input id="setting-motion" type="checkbox" ${s.settings.reduceMotion?'checked':''}></div>
 <div class="settings-row"><label for="setting-sensitivity">鼠标灵敏度</label><input id="setting-sensitivity" type="range" min="0.3" max="2" step="0.1" value="${s.settings.sensitivity}"></div>
 <div class="settings-row"><label for="setting-invert">反转鼠标 Y 轴</label><input id="setting-invert" type="checkbox" ${s.settings.invertY?'checked':''}></div>
 <div class="settings-row"><label for="setting-sound">轻音效<small>只在用户操作后播放；没有自动播放的背景音乐。</small></label><input id="setting-sound" type="checkbox" ${s.settings.sound?'checked':''}></div>
 <div class="settings-row"><label for="setting-volume">音效音量</label><input id="setting-volume" type="range" min="0" max="0.5" step="0.01" value="${s.settings.volume}"></div>
 <div class="settings-row"><label for="setting-text">界面文字基准</label><select id="setting-text">${[16,18,20].map(x=>`<option ${s.settings.textSize===x?'selected':''}>${x}</option>`).join('')}</select></div>
 <p class="help" style="margin-top:20px">访客记录依赖当前浏览器身份；连续 30 天未使用后可能清理。服务端需要持久磁盘。清理 Cookie 后无法自动证明原身份。</p>
 <div class="button-row">${button('clear-data','清除我的全部应用数据','btn small secondary')}${button('outbox','查看本机待同步','text-btn')}</div>`,{size:'narrow',footer:button('apply-settings','应用设置','btn')})}
async function commitSettings(){s.settings={...s.settings,quality:$('#setting-quality').value,autoQuality:$('#setting-auto').checked,reduceMotion:$('#setting-motion').checked,sensitivity:+$('#setting-sensitivity').value,invertY:$('#setting-invert').checked,sound:$('#setting-sound').checked,volume:+$('#setting-volume').value,textSize:+$('#setting-text').value};applySettings();closePanel();render();toast('已保存体验设置。')}
async function retryRenderer(){
 if(engine){if(!await engine.retryScene())return}
 else{await createEngine();if(!engine||engine.status==='error')return;if(s.world&&await engine.setScene(s.page,s.world,s.field,recoveryCheckpoint||s.journey?.checkpoint)===false)return;engine.setContents([...s.contentMap.values()])}
 recoveryCheckpoint=null;render();
}

function creditsPanel(){openPanel('credits','漫知录 · 关于这片森林','WANDERWISE LAND / 1.0.0',`<div class="credits"><p>以问题为起点，以空间探索为入口，以精神家园为沉淀场所。带走观点，也留下自己的思考。</p><h3>这个运行版包含什么？</h3><p>Three.js / ES Modules 前端、FastAPI / SQLite 后端；Blender 制作的书屋、KayKit 免费 CC0 家具、系统字体生成的中文标签、原创演示文章。应用不依赖外部 CDN，也不包含任何开发者密钥。</p><h3>来源与边界</h3><p>自带路线明确标记为演示。真实内容仅通过服务端知乎适配器取得，并标明来源与获取时间。搜索摘要不是全文。场域使用有来源段落的规则导览，不冒充模型理解。手工洞察不会伪称 AI 生成。</p><h3>资产说明</h3><p>书屋建筑与定制陈设由本项目制作，选用 Kay Lousberg 的 Furniture Bits 1.0 免费 CC0 家具；许可与文件哈希随包提供。Tiny Treats Lovely Living Room 付费包尚未取得。无字体二进制文件随包分发。第三方 Python 依赖按各自许可证使用。</p><h3>隐私与社区</h3><p>所有旅程、锚点和洞察默认私人。同频、OAuth 与聊天未开放。不会自动向知乎发布内容。无第三方统计脚本，无访客画像推断。</p><h3>验收状态</h3><p>完整外部验收需要在可访问官方接口的网络中核验、配置持久化 HTTPS 部署，并执行真实设备测试。详细结果和技术栈偏差见随包 TEST_REPORT 与 REQUIREMENTS_TRACEABILITY 文档。</p></div>`,{size:'narrow'})}
async function outboxPanel(){let entries=(await local.all('outbox')),drafts=(await local.all('drafts')).filter(x=>x.id.startsWith(api.owner+':'));openPanel('outbox','本机待同步与草稿','待同步不是保存成功。不同访客身份的旧操作不会自动迁移。',`<div class="notice">${entries.filter(e=>e.value.owner===api.owner).length} 项当前身份待同步 · ${drafts.length} 项当前身份草稿。检查点和未上传事件不会跨标签页自动覆盖服务端版本。</div>${entries.length?entries.map(e=>`<div class="anchor-card"><div class="context">${esc(e.value.method)} ${esc(e.value.path)} · ${date(e.value.queuedAt)}</div><p>${e.value.owner===api.owner?'属于当前访客':'旧访客身份，禁止自动迁移'}${e.value.error?' · '+esc(e.value.error):''}</p>${button('discard-pending','丢弃这项待同步','mini-btn',`data-id="${esc(e.id)}"`)}</div>`).join(''):empty('没有尚未确认的业务写入','收藏和私人锚点以服务端成功响应为准。')}${drafts.filter(d=>d.id.includes(':anchor:')||d.id.includes(':insight:')).map(d=>`<div class="anchor-card"><div class="context">本机文本草稿</div><p>${esc(d.value.text||d.value.coreInsight||'尚未填写文本')}</p><p class="help">可复制草稿后，在对应语境重新打开编辑器。</p></div>`).join('')}<div class="button-row">${button('sync-now','尝试同步当前身份操作','btn')}${button('journal','回到日志','text-btn')}</div>`)}
async function synchronize(){if(!s.session)return;await api.flush((result,v,e)=>{if(e)toast('有待同步操作需要处理：'+e.message,true)});await refreshPrivate();if(s.modal==='outbox')await outboxPanel();else if(!s.modal)render()}
let audio=null;
function sound(){if(!s.settings.sound)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();audio.resume();let osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(620,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(930,audio.currentTime+.15);gain.gain.setValueAtTime(.001,audio.currentTime);gain.gain.exponentialRampToValueAtTime(Math.max(.002,s.settings.volume),audio.currentTime+.025);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.4);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.41);osc.onended=()=>{osc.disconnect();gain.disconnect()}}catch{}}
async function perform(action,id,el){switch(action){
 case 'brand':case 'enter-home':return home();case 'close':return closePanel();case 'credits':return creditsPanel();case 'settings':return settingsPanel();case 'apply-settings':return commitSettings();case 'retry-scene':return retryRenderer();case 'retry-low-quality':s.settings.quality='low';s.settings.autoQuality=false;applySettings();return retryRenderer();case 'roam':if(s.readonly)return toast('当前只读，请从日志重新载入或显式接管。',true);return engine?.resume();case 'seed':return seedsPanel();case 'preset':{let p=s.presets.find(p=>p.id===id);return startWorld({seedMode:p.dataMode==='demo'?'demo':'preset',presetId:p.id})}case 'random-seed':{let ps=s.presets.filter(p=>p.dataMode==='demo'),p=ps[Math.floor(Math.random()*ps.length)];return startWorld({seedMode:'demo',presetId:p.id})}case 'knowledge-catalog':return catalogPanel();case 'knowledge':return startWorld({seedMode:'knowledge',presetId:id});case 'cancel-job':return cancelProgress();case 'bag':return bagPanel();case 'bag-filter':return bagPanel(id);case 'bag-edit':return editBag(id);
 case 'bag-source':{let b=s.bag.find(b=>b.id===id);if(b.targetType==='insight')return insightView(b.targetId);if(b.contentId)return readContent(b.contentId,b.excerptId);return toast('这是一个话题词，不是正文证据。')}
 case 'bag-remove':{let b=s.bag.find(b=>b.id===id),ls=(await api.call('/bag/links')).items.filter(l=>l.sourceBagItemId===id||l.targetBagItemId===id);if(await confirmDialog('从收藏库移除？',`只删除个人收藏关系，不删除原内容。${ls.length} 条手工连线也会删除；已保存洞察保留引用快照。`,'移除收藏')){await api.call('/bag/items/'+id,'DELETE');s.selected.delete(id);return bagPanel()}return bagPanel()}
 case 'collect-content':return collect('content',id);case 'collect-excerpt':return collect('excerpt',id);case 'read-content':return readContent(id);case 'enter-field':return enterField(id);case 'return-world':return returnWorld();case 'topic':return topicPanel(id);case 'expand-node':return expandNode(s.world.nodes.find(n=>n.id===id));case 'track-node':{let n=s.world.nodes.find(n=>n.id===id);closePanel();engine?.cycleNav(n);return updateNav()}case 'cancel-nav':if(engine)engine.navigation.mode=0;return updateNav();case 'anchor':return anchorEditor();case 'anchors':return anchorsPanel();case 'edit-anchor':return anchorEditor(id);
 case 'remove-anchor':if(await confirmDialog('删除这个私人想法？','删除后会从场景与日志同步移除。','删除锚点')){await api.call('/anchors/'+id,'DELETE');await refreshPrivate()}return anchorsPanel();
 case 'synthesis':case 'selected-synthesis':return synthesisPanel();case 'link-materials':return linkMaterials();case 'links-panel':return linksPanel();case 'remove-link':await api.call('/bag/links/'+id,'DELETE');return linksPanel();case 'journal':return journalPanel();case 'insights-tab':return journalPanel('insights');case 'insight-view':return insightView(id);case 'delete-insight':if(await confirmDialog('删除这份洞察？','其对应收藏和手工连线也会移除，源材料仍保留。','删除洞察')){await api.call('/insights/'+id,'DELETE');await refreshPrivate()}return journalPanel('insights');case 'map':return mapPanel();case 'journey-map':return mapPanel(id);case 'resume-journey':return loadJourney(id);case 'takeover':return loadJourney(s.journey.id,true);case 'remove-journey':if(await confirmDialog('删除这段私人旅程？','收藏、私人锚点与已保存洞察保留；仅删除旅程事件、检查点及其关联。','删除旅程')){await api.call('/journeys/'+id,'DELETE');if(s.journey?.id===id)await home({skipPause:true})}return journalPanel();case 'pause':return pausePanel();case 'pause-home':return pauseJourney();case 'local-home':return home({skipPause:true});case 'archive':return archiveJourney();case 'phone':return phonePanel();case 'outbox':return outboxPanel();case 'sync-now':return synchronize();case 'discard-pending':if(await confirmDialog('丢弃这项本机待同步操作？','未送达服务端的修改将被放弃。','丢弃'))await local.del('outbox',id);return outboxPanel();
 case 'clear-data':if(await confirmDialog('清除我的全部应用数据？','此访客的旅程、收藏、锚点、洞察和本机草稿将删除。其他访客与公共内容缓存不受影响。','永久清除')){await api.call('/me/data','DELETE',{confirm:'DELETE_MY_DATA'});for(let st of ['outbox','drafts','cache'])await local.clear(st);location.href='/'}return;
 }}
document.addEventListener('click',e=>{let el=e.target.closest('[data-action]');if(!el)return;e.preventDefault();Promise.resolve(perform(el.dataset.action,el.dataset.id,el)).catch(e=>toast(e.message,true))});
document.addEventListener('keydown',e=>{if(!s.modal)return;if(e.key==='Escape'){e.preventDefault();closePanel();return}if(e.key==='Tab'){let candidates=$$('#overlay-root button:not([disabled]),#overlay-root a,#overlay-root input:not([disabled]),#overlay-root textarea,#overlay-root select').filter(el=>el.offsetParent!==null),first=candidates[0],last=candidates.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
function engineAction(action,t){if(s.modal)return;let near=getContext();if(t?.node&&s.page==='world')contextNode=t.node;switch(action){case 'b':return bagPanel();case 'r':return anchorEditor();case 't':return anchorsPanel('context');case 'v':{let n=t?.node||near;engine.cycleNav(n);if(n)queueEvent('navigation_started',n.topicId);return updateNav()}case 'read':if(!t)return;if(t.type==='facility'&&({door:'seed',cabinet:'bag',synthesis:'synthesis',journal:'journal',phone:'phone'})[t.id]===t.action)return perform(t.action);if(t.type==='node'){if(dist(engine.player,t.position)>4)return toast('再靠近一点，才能阅读或收集。');return topicPanel(t.node.id)}return readContent(t.content.id,t.excerpt.id);case 'e':if(!t)return toast('先靠近一份可收集的金句。');if(dist(engine.player,t.position)>4)return toast('距离较远，无法收集。');return t.type==='excerpt'?collect('excerpt',t.excerpt.id):t.type==='node'?collect('topic',t.node.topicId):null;case 'f':if(t?.type==='excerpt')return enterField(t.content.id);return toast('靠近一份具有正文的金句，才能进入场域。')}}
function onSceneState(status,error=''){
 s.sceneState=status;s.sceneError=error;let el=$('#scene-load');if(!el){el=document.createElement('div');el.id='scene-load';document.body.append(el)}
 el.classList.toggle('hidden',status==='ready');
 el.innerHTML=status==='loading'?'<div class="scene-loading-card"><span class="eyebrow">林间灯火 · 知识书屋</span><h3>正在打开书屋</h3><p>准备家具、光线与安全落点…</p></div>':status==='error'?`<div class="scene-loading-card"><h3>小屋暂时没有准备好</h3><p>${esc(error)}</p><div class="button-row">${button('retry-scene','重新加载','btn')}${button('retry-low-quality','以低画质重试','btn secondary')}</div></div>`:'';
}
async function createEngine(){
 if(engine)return;if(engineCreation){await engineCreation;return createEngine()}
 if(needsCanvasReset){const canvas=$('#world');canvas.replaceWith(canvas.cloneNode(false));needsCanvasReset=false}
 engineCreation=(async()=>{
  try{const {Engine}=await import(rendererPreference==='legacy'?'./engine/legacy/engine.js':'./engine/engine.js');engine=new Engine($('#world'),{sceneState:onSceneState,notice:toast,action:(a,t)=>Promise.resolve(engineAction(a,t)).catch(e=>toast(e.message,true)),escape:()=>{if(s.modal)return;if(s.page!=='landing'&&s.page!=='home')pausePanel()},active:onActive,target:onTarget,near:n=>{if(s.page==='world')contextNode=n},visit:n=>{if(s.page==='world')queueEvent('topic_entered',n.topicId,{dwellSeconds:2},n.id)},leave:(n,t)=>{if(n&&s.page==='world')queueEvent('topic_left',n.topicId,{dwellSeconds:Math.min(t,120)},n.id)},navigation:updateNav,expand:n=>expandNode(n,true),contextLost:()=>{recoveryCheckpoint=engine?.checkpoint();engine?.dispose();engine=null;needsCanvasReset=true;onSceneState('error','三维画面暂时中断。已保存记录不受影响，请重试。')},metrics:m=>{diagnostics=m;let el=$('#diag');if(el)el.textContent=`3D · ${m.fps} FPS · ${m.drawCalls} DRAWS · ${Math.round(m.triangles/1000)}K TRIANGLES`}});await engine.ready;}catch{engine?.dispose();engine=null;onSceneState('error','暂时无法启动三维画面。请确认浏览器支持 WebGL2 并开启硬件加速，再重试。')}

 })();try{await engineCreation}finally{engineCreation=null}
}
async function init(){
 $('#app').innerHTML='<div class="loading-screen"><img src="/static/assets/mark.svg" alt=""><h2>漫知录</h2><p>正在整理家园与私人存档</p></div>';
 try{
  let session=await api.call('/session/guest','POST',{});api.csrf=session.csrfToken;api.owner=session.user.id;s.session=session;s.presets=(await api.call('/seeds')).items;await refreshPrivate();
  await createEngine();
  if(['127.0.0.1','localhost'].includes(location.hostname)&&new URLSearchParams(location.search).get('qa')==='1'){const {installRenderQA}=await import('./engine/render-qa.js');installRenderQA(()=>engine)}
  applySettings();render();await synchronize();let match=location.pathname.match(/^\/journeys\/([^/]+)/),canvasMatch=location.pathname.match(/^\/canvas\/([^/]+)/);if(match){await loadJourney(match[1]);let ev=await local.get('drafts',api.owner+':events:'+match[1]);eventsBuffer=ev?.value?.events||[]}else if(canvasMatch){s.page='home';render();await mapPanel(canvasMatch[1])}else if(location.pathname==='/home'){s.page='home';render()}else if(location.pathname==='/settings')settingsPanel();else if(location.pathname==='/credits')creditsPanel();
 }catch(e){$('#app').innerHTML=`<div class="loading-screen"><img src="/static/assets/mark.svg" alt=""><h2>家园暂时没有连接成功</h2><p>${esc(e.message)}</p><p>请确认通过启动脚本访问，不要直接双击 index.html。</p><div class="button-row" style="justify-content:center"><button class="btn primary" id="boot-retry">重新连接</button></div></div>`;$('#boot-retry').onclick=()=>location.reload()}
}
window.addEventListener('online',()=>synchronize().catch(()=>toast('网络已恢复，但服务仍不可达。',true)));
window.addEventListener('offline',()=>{engine?.pause();setSave('离线 · 修改待同步');toast('网络离线。已有内容仍可阅读，新增业务写入会明确保留为待同步。')});
window.addEventListener('popstate',()=>{let m=location.pathname.match(/^\/journeys\/([^/]+)/);if(m)loadJourney(m[1]).catch(e=>toast(e.message,true));else home().catch(e=>toast(e.message,true))});
setInterval(()=>{if(s.journey?.status==='active'&&!document.hidden&&!s.busy&&!s.readonly)saveCheckpoint().catch(()=>{})},10000);
setInterval(()=>{if(!document.hidden)flushEvents()},5000);
setInterval(()=>{if(s.session&&!document.hidden)api.call('/session/guest','POST',{}).then(session=>{if(session.user.id!==api.owner){engine?.pause();s.readonly=true;toast('访客身份已变化。旧草稿保留，请刷新后核对身份。',true);return}s.session=session;api.csrf=session.csrfToken}).catch(()=>{})},20*60000);
// Read-only diagnostics for manual QA. No credentials, private text or mutation bypasses exposed.
window.wanderwiseDiagnostics=()=>({page:s.page,renderer:engine?(engine.renderer.webgl?'three-webgl2':'native-webgl2'):'unavailable',sceneState:engine?.status||s.sceneState||'loading',sceneKind:engine?.kind,sceneStage:engine?.scene?.stage,eye:engine?.eye?.slice(),target:engine?.target?.id,active:engine?.active,facilities:engine?.kind==='home'?engine.scene?.targets?.map(t=>({id:t.id,position:{...t.position}})):undefined,assetBytes:engine?.scene?.assetBytes,position:engine?{...engine.player}:null,camera:engine?{...engine.camera}:null,metrics:{...diagnostics,...engine?.renderer?.metrics},pending:s.pending,worldVersion:s.world?.version,nodeCount:s.world?.nodes.length,modal:s.modal});
init();
