import {Renderer} from './renderer.js';
import {buildScene,playerGeometry,C} from './scenes.js';
import {Geometry,color} from './geometry.js';
import {clamp,mix,dist,segmentBox,pathBetween,project} from './math.js';
export class Engine{
 constructor(canvas,callbacks={}){
  this.canvas=canvas;this.callbacks=callbacks;this.renderer=new Renderer(canvas);this.keys=new Set();this.active=false;this.kind='home';this.player={x:0,y:0,z:5,yaw:0};this.camera={yaw:0,pitch:.22,distance:5};this.eye=[0,3,10];this.target=null;this.contents=new Map();this.anchors=[];this.settings={quality:'medium',sensitivity:1,reduceMotion:false,invertY:false,autoQuality:true};this.navigation={id:null,mode:0};this.last=performance.now();this.time=0;this.vy=0;this.grounded=true;this.aimSince=0;this.nearId=null;this.visitedSeconds=0;this.totalDwell=0;this.visited=false;this.busy=false;this.expansionAttempt=new Set();this.cleanup=[];
  let listen=(el,type,fn,options)=>{el.addEventListener(type,fn,options);this.cleanup.push(()=>el.removeEventListener(type,fn,options))};
  let typing=e=>e.isComposing||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||e.target.isContentEditable;
  listen(document,'keydown',e=>{if(e.defaultPrevented||typing(e)||e.repeat)return;if(e.code==='Escape'){this.pause();callbacks.escape?.();return}if(!this.active)return;this.keys.add(e.code);if(['Space','KeyE','KeyF','KeyB','KeyR','KeyT','KeyV'].includes(e.code))e.preventDefault();if(e.code==='Space'&&this.grounded){this.vy=3.96;this.grounded=false}if(['KeyE','KeyF','KeyB','KeyR','KeyT','KeyV'].includes(e.code))callbacks.action?.(e.code.slice(3).toLowerCase(),this.target)});
  listen(document,'keyup',e=>this.keys.delete(e.code));listen(window,'blur',()=>this.pause());listen(document,'visibilitychange',()=>{if(document.hidden)this.pause()});
  listen(document,'pointerlockchange',()=>{if(document.pointerLockElement!==canvas)this.pause(false)});
  listen(document,'mousemove',e=>{if(this.active&&document.pointerLockElement===canvas){this.camera.yaw-=e.movementX*.0023*this.settings.sensitivity;this.camera.pitch=clamp(this.camera.pitch+e.movementY*.0018*this.settings.sensitivity*(this.settings.invertY?-1:1),-.5,1.15)}});
  listen(canvas,'wheel',e=>{if(this.active){this.camera.distance=clamp(this.camera.distance+e.deltaY*.007,2,10);e.preventDefault()}},{passive:false});
  listen(canvas,'mousedown',e=>{if(e.button===0&&this.active)callbacks.action?.('read',this.target)});
  listen(canvas,'webglcontextlost',e=>{e.preventDefault();this.pause();callbacks.contextLost?.()});
  this.setScene('home');this.frame=this.frame.bind(this);this.raf=requestAnimationFrame(this.frame);
 }
 setScene(kind,world=null,field=null,checkpoint=null){this.pause();this.world=world;this.field=field;this.kind=kind;this.scene=buildScene(kind,world,field);this.renderer.upload('scene',this.scene.geometry);this.renderer.clearText();this.player={...(checkpoint?.position||this.scene.spawn),yaw:checkpoint?.yaw||0};this.camera={yaw:0,pitch:.22,distance:5,...checkpoint?.camera};this.navigation={id:checkpoint?.trackedNodeId||null,mode:checkpoint?.navigationMode||0};this.vy=0;this.grounded=true;this.target=null;this.nearId=null;this.visitedSeconds=0;this.visited=false;this.totalDwell=0;this.eye=[this.player.x,3,this.player.z+5];this.updateTargets();}
 updateWorld(w){let cp=this.checkpoint();this.setScene('world',w,null,cp)}
 setContents(contents){this.contents=new Map(contents.map(c=>[c.id,c]));this.updateTargets()}
 setAnchors(anchors){this.anchors=anchors}
 updateTargets(){if(!this.scene)return;this.targets=[...this.scene.targets];if(this.kind!=='home')for(let n of this.scene.nodes){let c=this.contents.get(n.contentIds[0]);if(!c)continue;let excerpts=this.kind==='field'?[{id:n.section.excerptId,text:n.section.text,kind:'original_excerpt'}]:c.excerpts.filter(e=>n.excerptIds.includes(e.id)).slice(0,2);for(let [i,e] of excerpts.entries())this.targets.push({id:e.id+'@'+n.id,type:'excerpt',node:n,content:c,excerpt:e,title:c.title,position:{x:n.position.x+(i?2.1:-1.8),y:1.7+i*.6,z:n.position.z+1.8}})}}
 async resume(){if(this.busy)return;try{await this.canvas.requestPointerLock();this.active=true;this.callbacks.active?.(true)}catch{this.callbacks.notice?.('浏览器未允许鼠标捕获；可使用简化阅读模式或下方设施入口。')}}
 pause(unlock=true){this.active=false;this.keys.clear();this.callbacks.active?.(false);if(unlock&&document.pointerLockElement===this.canvas)document.exitPointerLock()}
 nearest(){if(!this.scene.nodes.length)return null;return this.scene.nodes.reduce((a,b)=>dist(this.player,a.position)<dist(this.player,b.position)?a:b)}
 checkpoint(){return {position:{x:+this.player.x.toFixed(3),y:+this.player.y.toFixed(3),z:+this.player.z.toFixed(3)},yaw:this.player.yaw,camera:{...this.camera},trackedNodeId:this.navigation.id,navigationMode:this.navigation.mode}}
 clearKeys(){this.keys.clear()}
 cycleNav(node){if(!node)return this.callbacks.notice?.('先选择或瞄准一个话题，再开启追踪。');if(this.navigation.id!==node.id)this.navigation={id:node.id,mode:1};else this.navigation.mode=(this.navigation.mode+1)%3;this.callbacks.navigation?.(this.navigation,node)}
 obstructed(a,b){return this.scene.colliders.some(box=>{let hit=segmentBox(a,b,box);return hit!==null&&hit>.005&&hit<.97})}
 move(dx,dz){let p=this.player,r=.28;let attempt=(x,z)=>{if(this.kind==='home'&&(Math.abs(x)>8.6||z>7.65||z< -8.2))return false;if(Math.abs(x)>this.scene.boundary-2||Math.abs(z)>this.scene.boundary-2)return false;return !this.scene.colliders.some(b=>x+r>b.min[0]&&x-r<b.max[0]&&z+r>b.min[2]&&z-r<b.max[2]&&p.y+1.5>b.min[1]&&p.y<b.max[1])};if(attempt(p.x+dx,p.z))p.x+=dx;if(attempt(p.x,p.z+dz))p.z+=dz}
 frame(stamp){let dt=Math.min(.04,(stamp-this.last)/1000);this.last=stamp;this.time+=dt;let p=this.player;this.metricsAccumulator=(this.metricsAccumulator||[]);this.metricsAccumulator.push(dt);if(this.metricsAccumulator.length>300)this.metricsAccumulator.shift();let moving=false;
  if(this.active&&!document.hidden){let f=(this.keys.has('KeyW')?1:0)-(this.keys.has('KeyS')?1:0),s=(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0),l=Math.hypot(f,s);moving=l>0;if(l){f/=l;s/=l;let dx=(-Math.sin(this.camera.yaw)*f+Math.cos(this.camera.yaw)*s)*4.5*dt,dz=(-Math.cos(this.camera.yaw)*f-Math.sin(this.camera.yaw)*s)*4.5*dt;this.move(dx,dz);p.yaw=Math.atan2(-dx,-dz)}
   this.vy-=9.81*dt;p.y+=this.vy*dt;let floor=this.scene.height(p.x,p.z);if(p.y<=floor){p.y=floor;this.vy=0;this.grounded=true}if(p.y< -10){Object.assign(p,this.scene.spawn);this.vy=0;this.callbacks.notice?.('已返回安全落点，已保存的收获仍在。')}
  }
  let target=[p.x,p.y+1.18,p.z],d=this.camera.distance,ideal=[p.x+Math.sin(this.camera.yaw)*Math.cos(this.camera.pitch)*d,p.y+1.18+Math.sin(this.camera.pitch)*d,p.z+Math.cos(this.camera.yaw)*Math.cos(this.camera.pitch)*d];let fraction=1;for(let b of this.scene.colliders){let t=segmentBox(target,ideal,b,.16);if(t!==null)fraction=Math.min(fraction,Math.max(.1,t-.045))}ideal=target.map((v,i)=>mix(v,ideal[i],fraction));let factor=1-Math.exp(-dt*12);this.eye=this.eye.map((v,i)=>mix(v,ideal[i],factor));this.eye[1]=Math.max(this.eye[1],this.scene.height(this.eye[0],this.eye[2])+.3);
  this.renderer.begin(this.eye,target,{fog:this.kind==='home'?[.33,.31,.24]:[.49,.66,.59],fogDistance:this.kind==='home'?85:130,quality:this.settings.quality});this.renderer.draw('scene');let dynamic=playerGeometry(p,this.settings.reduceMotion?0:this.time,moving);dynamic.transform=null;
  // Persisted private anchors only, rendered as small lanterns at stable node-relative offsets.
  if(this.kind==='world')for(let a of this.anchors){let n=this.scene.nodes.find(n=>n.topicId===a.topicId);if(n&&dist(p,n.position)<32){let x=n.position.x+a.localOffset.x,z=n.position.z+a.localOffset.z;dynamic.cylinder(x,0,z,.18,.8,C.gold,6,.1);dynamic.rock(x,.8,z,.12,C.cream)}}
  if(this.kind==='world'&&this.navigation.mode){let dest=this.scene.nodes.find(n=>n.id===this.navigation.id),near=this.nearest();if(dest&&near&&dist(p,dest.position)>6){let path=pathBetween(this.scene.nodes,this.scene.links,near.id,dest.id);if(path.length===1)path=[{x:p.x,y:0,z:p.z},...path];for(let i=1;i<path.length;i++){let a=path[i-1],b=path[i],length=dist(a,b);if(this.navigation.mode===2||this.settings.reduceMotion){for(let t=0;t<length;t+=2.4){let f=t/length,v=Math.min(1,(t+1.3)/length);dynamic.path({x:mix(a.x,b.x,f),z:mix(a.z,b.z,f)},{x:mix(a.x,b.x,v),z:mix(a.z,b.z,v)},.14,C.cream,.13)}}else for(let j=0;j<9;j++){let f=(j/9+this.time*.11)%1;dynamic.rock(mix(a.x,b.x,f),.45+Math.sin(f*6)*.1,mix(a.z,b.z,f),.055,C.cream)}}}}
  this.renderer.upload('dynamic',dynamic.data(),true);this.renderer.draw('dynamic');
  this.drawLabels();this.pickTarget();this.trackVisits(dt);
  if(stamp-(this.lastMetrics||0)>1000){this.lastMetrics=stamp;let avg=this.metricsAccumulator.reduce((a,b)=>a+b,0)/this.metricsAccumulator.length;this.callbacks.metrics?.({...this.renderer.metrics,fps:Math.round(1/avg)});if(this.settings.autoQuality&&this.active&&this.settings.quality!=='low'&&avg>1/30&&stamp-(this.lastDowngrade||0)>60000){this.settings.quality='low';this.lastDowngrade=stamp;this.callbacks.notice?.('帧率偏低，已自动切换低画质；可在设置中关闭自动调整。')}}
  this.raf=requestAnimationFrame(this.frame);
 }
 drawLabels(){let p=this.player;if(this.kind==='home'){for(let l of this.scene.labels){if(!this.obstructed(this.eye,l.position))this.renderer.text(l)}return}
  let near=this.scene.nodes.slice().sort((a,b)=>dist(p,a.position)-dist(p,b.position));for(let n of near.slice(0,12)){let d=dist(p,n.position),pos=[n.position.x,3.25,n.position.z];if(d<95&&!this.obstructed(this.eye,pos))this.renderer.text({text:n.title,position:pos,height:d>30?1.25:.86,tint:d<12?[1,.94,.74]:[.91,.98,.9]});if(d<30&&!this.obstructed(this.eye,[pos[0],2.63,pos[2]]))this.renderer.text({text:this.kind==='field'?'正文段落 · 可溯源':(n.biome==='forest'?'林地':n.biome==='lake'?'湖畔':n.biome==='meadow'?'旷野':'遗迹')+' · '+(n.expansionState==='expanded'?'已展开':'沿路探索'),position:[pos[0],2.6,pos[2]],height:.28,tint:[.78,.92,.81]})}
  let count=0;for(let t of this.targets){if(t.type!=='excerpt')continue;let distance=dist(p,t.node.position);t.lod=t.lod?distance<14:distance<12;if(t.lod&&count<8){let pos=[t.position.x,t.position.y,t.position.z];if(!this.obstructed(this.eye,pos)){let txt=t.excerpt.text;this.renderer.text({text:txt.length>68?txt.slice(0,65)+'…':txt,position:pos,height:.31,maxChars:22,tint:[1,.97,.84]});count++}}}
 }
 pickTarget(){let candidates=[];for(let t of this.targets){let d=dist(this.player,t.position);if(t.type==='excerpt'&&!t.lod)continue;if(t.type==='facility'&&d>4.5)continue;if(t.type==='excerpt'&&d>4)continue;let pos=[t.position.x,t.position.y,t.position.z],screen=project(pos,this.renderer.vp);if(screen[2]<0||Math.abs(screen[0])>.35||Math.abs(screen[1])>.24||this.obstructed(this.eye,pos))continue;let score=Math.hypot(screen[0],screen[1]);if(score<(t.type==='excerpt'?.26:.18))candidates.push({t,score,d})}candidates.sort((a,b)=>a.d-b.d||a.score-b.score);let selected=candidates[0]?.t||null;if(selected?.id!==this.aimId){this.aimId=selected?.id;this.aimSince=this.time}if(this.time-this.aimSince>.1&&this.target?.id!==selected?.id){this.target=selected;this.callbacks.target?.(selected,selected?dist(this.player,selected.position):0)}}
 trackVisits(dt){if(!this.active||this.kind==='home')return;let n=this.nearest(),id=n&&dist(this.player,n.position)<10?n.id:null;if(id!==this.nearId){if(this.visited&&this.nearId)this.callbacks.leave?.(this.scene.nodes.find(x=>x.id===this.nearId),this.totalDwell);this.nearId=id;this.visitedSeconds=0;this.totalDwell=0;this.visited=false;this.callbacks.near?.(id?n:null)}if(id){this.visitedSeconds+=dt;this.totalDwell+=dt;if(!this.visited&&this.visitedSeconds>=2){this.visited=true;this.callbacks.visit?.(n)}}if(this.kind==='world'&&n&&dist(this.player,n.position)<18&&n.expansionState==='unexpanded'&&this.visitedSeconds>.8&&!this.expansionAttempt.has(n.id)&&this.world.nodes[0].id!==n.id){this.expansionAttempt.add(n.id);this.callbacks.expand?.(n)}}
 dispose(){cancelAnimationFrame(this.raf);this.pause();this.cleanup.forEach(f=>f());this.renderer.dispose()}
}
