import {multiply,perspective,lookAt,project} from './math.js';
// This renderer is original project code, using the standard WebGL2 API. No CDN or font binaries.
const VS=`#version 300 es
precision highp float;layout(location=0)in vec3 p;layout(location=1)in vec3 n;layout(location=2)in vec3 c;uniform mat4 vp;uniform vec3 eye;out vec3 C;out float D;void main(){gl_Position=vp*vec4(p,1.);float sun=max(dot(n,normalize(vec3(-.45,.85,.35))),0.);float sky=.50+.18*max(n.y,0.);C=c*(sky+.48*sun);D=distance(eye,p);}`;
const FS=`#version 300 es
precision highp float;in vec3 C;in float D;uniform vec3 fog;uniform float fogDistance;out vec4 outColor;void main(){float f=1.-exp(-pow(D/fogDistance,2.));outColor=vec4(mix(C,fog,clamp(f,0.,.99)),1.);}`;
const TVS=`#version 300 es
precision highp float;layout(location=0)in vec2 p;uniform mat4 vp;uniform vec3 center;uniform vec3 right;uniform vec3 up;uniform vec2 size;out vec2 uv;void main(){uv=p*.5+.5;gl_Position=vp*vec4(center+right*p.x*size.x*.5+up*p.y*size.y*.5,1.);}`;
const TFS=`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D tex;uniform vec3 tint;uniform float opacity;out vec4 outColor;void main(){float d=texture(tex,vec2(uv.x,1.-uv.y)).r;float w=max(fwidth(d),.025);float a=smoothstep(.5-w,.5+w,d);if(a<.025)discard;outColor=vec4(tint,a*opacity);}`;
function program(gl,vs,fs){let shaders=[gl.VERTEX_SHADER,gl.FRAGMENT_SHADER].map((kind,i)=>{let s=gl.createShader(kind);gl.shaderSource(s,i?fs:vs);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s});let p=gl.createProgram();for(let s of shaders)gl.attachShader(p,s);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));shaders.forEach(s=>gl.deleteShader(s));return p}
function uniforms(gl,p,names){return Object.fromEntries(names.map(n=>[n,gl.getUniformLocation(p,n)]))}
function distanceField(mask,w,h,inside){let d=new Float32Array(w*h);for(let i=0;i<d.length;i++)d[i]=(mask[i*4+3]>127)===inside?0:10000;for(let y=0;y<h;y++)for(let x=0;x<w;x++){let i=y*w+x;if(x)d[i]=Math.min(d[i],d[i-1]+1);if(y)d[i]=Math.min(d[i],d[i-w]+1);if(x&&y)d[i]=Math.min(d[i],d[i-w-1]+1.4142);if(y&&x+1<w)d[i]=Math.min(d[i],d[i-w+1]+1.4142)}for(let y=h-1;y>=0;y--)for(let x=w-1;x>=0;x--){let i=y*w+x;if(x+1<w)d[i]=Math.min(d[i],d[i+1]+1);if(y+1<h)d[i]=Math.min(d[i],d[i+w]+1);if(x+1<w&&y+1<h)d[i]=Math.min(d[i],d[i+w+1]+1.4142);if(x&&y+1<h)d[i]=Math.min(d[i],d[i+w-1]+1.4142)}return d}
export class Renderer{
 constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false,preserveDrawingBuffer:false});if(!this.gl)throw Error('WebGL2 unavailable');let g=this.gl;this.p=program(g,VS,FS);this.u=uniforms(g,this.p,['vp','eye','fog','fogDistance']);this.tp=program(g,TVS,TFS);this.tu=uniforms(g,this.tp,['vp','center','right','up','size','tex','tint','opacity']);this.batches=new Map();this.textures=new Map();this.tvao=g.createVertexArray();g.bindVertexArray(this.tvao);this.tbuf=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,this.tbuf);g.bufferData(g.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,1,1,-1,-1,1,1,-1,1]),g.STATIC_DRAW);g.enableVertexAttribArray(0);g.vertexAttribPointer(0,2,g.FLOAT,false,0,0);g.enable(g.DEPTH_TEST);g.disable(g.CULL_FACE);this.metrics={drawCalls:0,triangles:0};}
 upload(name,data,dynamic=false){let g=this.gl,b=this.batches.get(name);if(!b){b={vao:g.createVertexArray(),buf:g.createBuffer(),count:0};this.batches.set(name,b)}g.bindVertexArray(b.vao);g.bindBuffer(g.ARRAY_BUFFER,b.buf);g.bufferData(g.ARRAY_BUFFER,data,dynamic?g.DYNAMIC_DRAW:g.STATIC_DRAW);for(let i=0;i<3;i++){g.enableVertexAttribArray(i);g.vertexAttribPointer(i,3,g.FLOAT,false,36,i*12)}b.count=data.length/9}
 clearText(){let g=this.gl;for(let t of this.textures.values())g.deleteTexture(t.tex);this.textures.clear()}
 textTexture(text,maxChars=20){let key=maxChars+':'+text;if(this.textures.has(key)){let v=this.textures.get(key);this.textures.delete(key);this.textures.set(key,v);return v}let canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true}),font='500 40px "Noto Serif CJK SC", "Songti SC", "SimSun", serif';ctx.font=font;let lines=[],line='';for(let char of text){if(char==='\n'||[...line].length>=maxChars){lines.push(line);line='';if(char==='\n')continue}line+=char}if(line)lines.push(line);lines=lines.slice(0,4);let width=Math.min(1024,Math.ceil(Math.max(1,...lines.map(l=>ctx.measureText(l).width))+32)),height=lines.length*56+28;canvas.width=width;canvas.height=height;ctx.font=font;ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='top';lines.forEach((l,i)=>ctx.fillText(l,width/2,14+i*56));let pixels=ctx.getImageData(0,0,width,height).data,ins=distanceField(pixels,width,height,true),out=distanceField(pixels,width,height,false),sdf=new Uint8Array(width*height);for(let i=0;i<sdf.length;i++)sdf[i]=Math.max(0,Math.min(255,128+(out[i]-ins[i])*16));let g=this.gl,tex=g.createTexture();g.bindTexture(g.TEXTURE_2D,tex);g.pixelStorei(g.UNPACK_ALIGNMENT,1);g.texImage2D(g.TEXTURE_2D,0,g.R8,width,height,0,g.RED,g.UNSIGNED_BYTE,sdf);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);let v={tex,aspect:width/height,lines:lines.length};this.textures.set(key,v);if(this.textures.size>80){let k=this.textures.keys().next().value;g.deleteTexture(this.textures.get(k).tex);this.textures.delete(k)}return v}
 begin(eye,target,{fog=[.43,.62,.57],fogDistance=125,quality='medium'}={}){let g=this.gl,dpr=quality==='low'?1:Math.min(devicePixelRatio,quality==='high'?2:1.4),w=Math.floor(this.canvas.clientWidth*dpr),h=Math.floor(this.canvas.clientHeight*dpr);if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h}g.viewport(0,0,w,h);g.clearColor(...fog,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);let view=lookAt(eye,target);this.vp=multiply(perspective(65*Math.PI/180,w/h,.08,650),view);this.right=[view[0],view[4],view[8]];this.up=[view[1],view[5],view[9]];this.metrics={drawCalls:0,triangles:0};g.disable(g.BLEND);g.depthMask(true);g.useProgram(this.p);g.uniformMatrix4fv(this.u.vp,false,this.vp);g.uniform3fv(this.u.eye,eye);g.uniform3fv(this.u.fog,fog);g.uniform1f(this.u.fogDistance,fogDistance)}
 draw(name){let g=this.gl,b=this.batches.get(name);if(!b||!b.count)return;g.useProgram(this.p);g.bindVertexArray(b.vao);g.drawArrays(g.TRIANGLES,0,b.count);this.metrics.drawCalls++;this.metrics.triangles+=b.count/3}
 text(label){let g=this.gl,p=project(label.position,this.vp);if(p[2]<0||Math.abs(p[0])>1.4||Math.abs(p[1])>1.4)return;let t=this.textTexture(label.text,label.maxChars||20),height=(label.height||.75)*t.lines;g.useProgram(this.tp);g.bindVertexArray(this.tvao);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.depthMask(false);g.uniformMatrix4fv(this.tu.vp,false,this.vp);g.uniform3fv(this.tu.center,label.position);g.uniform3fv(this.tu.right,this.right);g.uniform3fv(this.tu.up,this.up);g.uniform2f(this.tu.size,height*t.aspect,height);g.uniform3fv(this.tu.tint,label.tint||[1,.97,.82]);g.uniform1f(this.tu.opacity,label.opacity??1);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,t.tex);g.uniform1i(this.tu.tex,0);g.drawArrays(g.TRIANGLES,0,6);this.metrics.drawCalls++;this.metrics.triangles+=2;g.depthMask(true)}
 dispose(){let g=this.gl;this.clearText();for(let b of this.batches.values()){g.deleteBuffer(b.buf);g.deleteVertexArray(b.vao)}g.deleteBuffer(this.tbuf);g.deleteVertexArray(this.tvao);g.deleteProgram(this.p);g.deleteProgram(this.tp)}
}
