/* Graph-local AI orchestration. Network is optional; no request on render/hover. */
(() => {
  'use strict';
  const P=ZGExperience.GalaxyExplorer.prototype,A=ZGAISemantic,S=ZGSpatial,C=ZGCore;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const COPY=['label','parent','parents','links','pos','answerIds','evidenceAnswerIds','assignedAnswerIds','support','df','source','aiRepair','aiSelected','aiQuote','aiEvidenceIds','aiSelectedFor'];
  P.aiSend=async function(action,extra={}){if(!globalThis.chrome?.runtime?.id)throw new Error('普通演示网页不接入云端 API，请加载扩展后配置');const r=await chrome.runtime.sendMessage({type:'ZH_GALAXY_AI_'+action,...extra});if(!r?.ok)throw new Error(r?.error||'AI 后台未响应');return r.data;};
  P.loadAIConfig=async function(){if(!this.running)return;try{const config=await this.aiSend('CONFIG');if(this.aiConfig&&this.aiConfig.revision!==config.revision){this.cancelAI('AI 配置已变化');this.autoAttempted=false;this.aiCache.clear();}this.aiConfig=config;}catch(e){this.aiConfig={enabled:false,consent:false,hasKey:false};}this.refreshAIUI();this.scheduleAI();};
  P.refreshAIUI=function(){if(!this.root)return;const c=this.aiConfig||{},status=this.$('.zg-ai-status'),chip=this.$('.zg-ai-chip');const summary=this.aiMessage||(c.enabled&&c.consent?`已启用 ${c.provider} / ${c.model} · ${c.hasKey?'密钥已配置':'未保存密钥（自定义本机服务可不填）'}`:'AI 未启用 · 当前使用本地算法');if(status)status.textContent=summary;if(chip){chip.textContent=this.aiBusy?'◇ AI 校对中':this.aiAudit?.length?`◇ AI 修正 ${this.aiAudit.length}`:c.enabled?'◇ AI 待校对':'◇ 本地语义';chip.title=summary;}
    const run=this.$('[data-action="ai-run"]'),undo=this.$('[data-action="ai-undo"]'),cancel=this.$('[data-action="ai-cancel"]');if(run)run.disabled=!!this.aiBusy;if(cancel)cancel.disabled=!this.aiBusy;if(undo)undo.disabled=!this.aiUndo||!!this.aiBusy;const audit=this.$('.zg-ai-audit');if(audit)audit.innerHTML=(this.aiAudit||[]).map(r=>`<div><b>${esc(r.oldLabel)} → ${esc(r.label)}</b><small>${esc(r.reason)} · ${r.accepted.length} 篇复核通过；本地命中 ${r.stats?.matched??'—'} / ${r.stats?.pool??'—'}，发送 ${r.stats?.sent??'—'} 篇</small></div>`).join('')+(this.aiTelemetry?`<p>本轮 ${this.aiTelemetry.requests} 次 API 请求 · ${Math.round(this.aiTelemetry.durationMs)} ms（含本地召回 / 网络）${this.aiTelemetry.cached?' · 命中本会话缓存':''}</p>`:'');};
  P.scheduleAI=function(){clearTimeout(this.aiTimer);if(!this.running||this.aiBusy||this.autoAttempted||!this.aiConfig?.enabled||!this.aiConfig?.auto||!this.aiConfig?.consent||this.progress?.phase==='loading')return;const epoch=this.graphEpoch;this.aiTimer=setTimeout(()=>{if(this.running&&!this.autoAttempted&&epoch===this.graphEpoch){this.autoAttempted=true;this.runAI();}},1800);};
  P.cancelAI=function(reason='已取消 AI 校对；本地星系保持可用'){if(!this.aiBusy)return;this.aiRunSerial++;const runId=this.currentAIRun;this.aiBusy=false;this.aiMessage=reason;this.aiSend('CANCEL',{runId}).catch(()=>{});this.refreshAIUI();};
  P.runAI=async function(){if(this.aiBusy)return;await this.ready;const config=this.aiConfig;if(!config?.enabled||!config.consent){this.aiMessage='请先配置供应商 / 模型 / API Key 并确认片段发送授权';this.refreshAIUI();return;}
    this.autoAttempted=true;this.aiBusy=true;const serial=++this.aiRunSerial,runId=C.uid('ai'),epoch=this.graphEpoch,settings=S.cleanSettings(this.settings),started=performance.now();this.currentAIRun=runId;this.aiTelemetry={requests:0,durationMs:0,cached:false};const alive=()=>this.running&&this.aiRunSerial===serial&&this.graphEpoch===epoch;
    try{const key=A.fingerprint(this.graph,settings)+':'+[config.revision,config.provider,config.model,config.threshold,config.candidateLimit].join(':');let patches=this.aiCache.get(key);
      if(patches){this.aiTelemetry.cached=true;}else{this.aiMessage='1 / 3 · 一次扫描现有关键词与少量支持句';this.refreshAIUI();const scan=A.scanInput(this.graph,settings);this.aiTelemetry.requests++;const first=await this.aiSend('RUN',{task:'scan',data:scan,runId});if(!alive())return;const repairs=A.validateRepairs(first.result,scan);if(!repairs.length){this.aiMessage='AI 未提出有证据的必要修正；保留本地星系';return;}
        this.aiMessage=`2 / 3 · 本地倒排召回 ${repairs.length} 个修正词的候选`;this.refreshAIUI();await new Promise(r=>setTimeout(r,0));if(!alive())return;const index=await A.CandidateIndex.create(this.graph.answers,alive);this.aiCandidateIndex=index;const groups=[];for(const r of repairs){if(!alive())return;const g=index.retrieve(r,settings,config);if(g.candidates.length)groups.push(g);await new Promise(resolve=>setTimeout(resolve,0));}if(!groups.length){this.aiMessage='本地没有召回可核验的文章，不提交无证据的改名';return;}
        this.aiMessage=`3 / 3 · 批量复核 ${groups.reduce((s,g)=>s+g.candidates.length,0)} 份候选摘要，每个词至多选 8 篇`;this.refreshAIUI();this.aiTelemetry.requests++;const second=await this.aiSend('RUN',{task:'select',data:{question:this.graph.question.title,priority:settings.sortMode,groups},runId});if(!alive())return;patches=A.validateSelections(second.result,groups,repairs,settings,this.graph.byAnswer);this.aiCache.set(key,C.clone(patches));while(this.aiCache.size>8)this.aiCache.delete(this.aiCache.keys().next().value);}
      if(!alive())return;if(!patches.length){this.aiMessage='AI 未找到充分的原文支持，本轮不修改词语或布局';return;}this.commitAI(patches);this.aiMessage=`已修正 ${patches.length} 个词，精选 ${patches.reduce((s,p)=>s+p.accepted.length,0)} 篇关联（跨主题可能重合）；节点 ID 与收藏保留`;this.toast(this.aiMessage,5500);
    }catch(e){if(alive()){this.aiMessage='AI 未完成：'+(e.message||String(e))+'。本轮未提交，继续使用现有星系。';this.toast(this.aiMessage,7000);}}finally{if(this.aiRunSerial===serial){this.aiBusy=false;this.aiTelemetry.durationMs=performance.now()-started;this.refreshAIUI();}}};
  P.commitAI=function(patches){
    // Validate the entire patch against the current graph before changing anything.
    const verified=patches.filter(r=>this.nodeById(r.id)&&A.validLabel(r.label)&&r.accepted.length<=8&&r.accepted.every(a=>this.answerNodes.has(a.id)&&this.graph.byAnswer.get(a.id)?.text.includes(a.quote)));if(verified.length!==patches.length)throw new Error('待提交修正与当前回答池不一致');
    this.aiUndo={nodes:new Map(this.nodes.map(n=>[n.id,Object.fromEntries(COPY.filter(k=>k in n).map(k=>[k,C.clone(n[k])]))])),audit:C.clone(this.aiAudit||[])};
    const fixedIds=new Set(verified.map(r=>r.id)),selectedByAnswer=new Map();for(const r of verified)for(const a of r.accepted){if(!selectedByAnswer.has(a.id))selectedByAnswer.set(a.id,[]);selectedByAnswer.get(a.id).push({repair:r,evidence:a});}
    const index=this.aiCandidateIndex||new A.CandidateIndex(this.graph.answers),alternative=n=>{const fs=index.docs.get(n.answerId)||new Set();let best=null,bestScore=.12;for(const candidate of this.graph.keywords){if(fixedIds.has(candidate.id))continue;const qs=A.features(candidate.label);let hits=0;for(const q of qs)if(fs.has(q))hits++;const score=hits/Math.max(1,qs.size);if(score>bestScore){bestScore=score;best=candidate;}}return best?.id||'__question__';};
    for(const r of verified){const n=this.nodeById(r.id);n.aiRepair={oldLabel:n.label,reason:r.reason,version:A.VERSION};n.label=r.label;n.source='ai-repaired';n.aiEvidenceIds=r.accepted.map(a=>a.id);n.answerIds=[...n.aiEvidenceIds];n.evidenceAnswerIds=[...n.aiEvidenceIds];n.support=n.aiEvidenceIds.length;}
    for(const n of this.graph.satellites){const selections=selectedByAnswer.get(n.answerId);let changed=false;if(selections){const chosen=selections[0];n.links=[...new Set([...(n.links||[]),n.parent,...selections.map(x=>x.repair.id)])].filter(id=>id!==chosen.repair.id&&this.nodeMap.has(id));n.parent=chosen.repair.id;n.aiSelected=true;n.aiSelectedFor=selections.map(x=>x.repair.id);n.aiQuote=chosen.evidence.quote;changed=true;}else if(fixedIds.has(n.parent)){n.parent=alternative(n);n.links=(n.links||[]).filter(id=>!fixedIds.has(id));delete n.aiSelected;delete n.aiQuote;delete n.aiSelectedFor;changed=true;}
      if(changed){const parent=this.nodeById(n.parent),centre=parent?.pos||{x:0,y:0,z:0},seed=S.hash(n.id),y=((seed%1000)/500)-1,rr=Math.sqrt(1-y*y),a=(seed%6283)/1000,r=parent?14:42;this.physics.anchors.set(n.id,{x:centre.x+Math.cos(a)*rr*r,y:centre.y+y*r,z:centre.z+Math.sin(a)*rr*r});}}
    for(const n of [...this.graph.keywords,...this.graph.phenomena])n.assignedAnswerIds=this.graph.satellites.filter(s=>s.parent===n.id).map(s=>s.answerId);
    this.aiAudit=verified;this.physics.setNodes(this.nodes);this.physics.wake(280);this.graphEpoch++;this.lastPreviewRefresh=0;this.cardsIds=[];this.layoutKey=null;this.dirty=true;if(this.selected)this.showPanel(this.selected);if(this.search&&this.panelMode==='search')this.searchChanged();
  };
  P.undoAI=function(){if(!this.aiUndo)return;this.cancelAI();for(const n of this.nodes){const old=this.aiUndo.nodes.get(n.id);if(!old)continue;for(const k of COPY)delete n[k];Object.assign(n,C.clone(old));this.physics.anchors.set(n.id,{...n.pos});}this.aiAudit=this.aiUndo.audit;this.aiUndo=null;this.aiCache.clear();this.indexGraph();this.physics.stop();this.aiMessage='已撤销最近一轮 AI 修正；词语、邻接与位置恢复，收藏保留';this.cardsIds=[];this.lastPreviewRefresh=0;this.refreshAIUI();if(this.selected)this.showPanel(this.selected);this.toast(this.aiMessage);};
})();
