/* 0.7 presentation: actual XYZ projection, world-anchored holograms, parameterized motion. */
(() => {
  'use strict';
  const S=ZGSpatial,C=ZGCore,A=ZGAISemantic,P=ZGExperience.GalaxyExplorer.prototype;
  const F='-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const {clamp,add,sub,dot,norm,cross,rgba,mix}=S;
  const base={};for(const k of ['renderShell','indexGraph','resize','applyAppearance','action','pointerMove','update','destroy','replaceQuestion','setProgress','showPanel','chooseAttention','home','focus','keydown'])base[k]=P[k];
  const range=(name,title,min,max,step='0.05',note='')=>`<label class="zg-control"><span>${title}${note?`<small>${note}</small>`:''}</span><div><input data-setting="${name}" type="range" min="${min}" max="${max}" step="${step}"><output data-for="${name}"></output></div></label>`;
  const checkbox=(name,label)=>`<label class="zg-checkbox"><input data-setting="${name}" type="checkbox">${label}</label>`;
  P.renderShell=function(){
    this.settings=S.cleanSettings({...S.DEFAULT,...this.options.settings});this.aiState='local';this.graphEpoch=0;this.aiCache=new Map();this.aiAudit=[];this.aiRunSerial=0;
    base.renderShell.call(this);this.root.classList.add('zg-3d');this.$('.zg-kicker span:last-child').textContent=' / SEMANTIC GALAXY · 0.7.1';
    this.$('.zg-dock-heading>span').textContent='固定阅读窗';this.$('.zg-help').textContent='WASD 转动视角 · Space 远离 · Shift 拉近 · 左键点亮邻接 · 双击聚焦 · 右键仔细阅读';
    this.$('.zg-actions').insertAdjacentHTML('afterbegin','<button data-action="freeze" class="zg-freeze-button" title="暂停力布局，不影响旋转与缩放">冻结空间</button>');
    this.$('.zg-toolbar').insertAdjacentHTML('beforeend','<button class="zg-ai-chip" data-action="ai-tab" title="配置 AI 关键词校对">◇ 本地语义</button>');
    this.$('.zg-settings').innerHTML=`<form method="dialog"><div class="zg-settings-head"><div><b>调校你的星系</b><small>三维空间 · 全息选段 · AI 校对</small></div><button value="cancel" aria-label="关闭设置">×</button></div><div class="zg-setting-tabs"><button type="button" data-action="settings-tab" data-value="space" aria-pressed="true">空间</button><button type="button" data-action="settings-tab" data-value="color">配色</button><button type="button" data-action="settings-tab" data-value="ai">AI 校对</button><button type="button" data-action="settings-tab" data-value="reading">读取与轨迹</button></div>
      <section data-section="space"><p class="zg-hint">拖动即预览，应用后保存。力只作用于 XYZ 世界坐标，不再为避让而挪动屏幕投影。</p>
      ${range('attraction','节点引力',0,3,'0.05','连边上的拉力；0 关闭')}${range('repulsion','节点斥力',0,4,'0.05','越大越疏；0 关闭')}${range('nodeScale','全部节点尺寸',.4,2.5)}${range('answerScale','回答 / 主题大小比',.4,2.5)}${range('rotationSpeed','角度旋转速度',.1,3)}${range('zoomSpeed','滚轮缩放速度',.2,2.5)}
      <label>运动模式<select data-setting="motion"><option value="comfort">舒适 · 手动转向，无惯性漂移</option><option value="explore">探索 · 更灵敏的手动转向</option><option value="still">静读 · 保留三维，锁定转向</option></select></label>${checkbox('layoutFrozen','冻结力布局（旋转和缩放仍可操作）')}
      <div class="zg-form-divider"></div><h3>全息选段</h3>${range('cardCount','同时出现的选段',1,8,'1')}${range('holoScale','选段空间尺寸',.65,1.7)}${range('holoOpacity','悬浮文字亮度',.35,1)}${checkbox('showReadingDock','同时显示固定阅读窗（辅助长时间阅读）')}<p class="zg-hint">原文信号不再使用消息框，而是以发光文字悬浮在空间里，并由节点引出折线定位到对应原文。指向 / 选中的回答优先展示。</p><div class="zg-row-actions"><button type="button" data-action="relayout">重新舒展当前布局</button><button type="button" data-action="reset-space">重置空间参数</button></div></section>
      <section data-section="color" hidden><div class="zg-theme-grid">${Object.entries(S.PALETTES).map(([id,p])=>`<button type="button" data-action="theme" data-value="${id}"><span class="zg-theme-swatches"><i style="background:${p.keyword}"></i><i style="background:${p.phenomenon}"></i><i style="background:${p.answer}"></i></span><b>${p.name}</b><small>${id==='tech'?'科技深黑 / 蓝紫青':id==='saturated'?'橙色 / 砖红 / 青绿':'莫兰迪 / 低饱和'}</small></button>`).join('')}</div><label>节点染色<select data-setting="nodeColorMode"><option value="uniform">统一主题色</option><option value="lineage">谱系染色 · 关键词随机 / 话题渐变 / 文章继承</option></select></label><p class="zg-hint">保留三套心情配色；另可切换到“谱系染色”，让基础关键词随机着色、交汇话题做渐变融合、具体文章继承所属话题的平均色，更容易看出脉络。</p><div class="zg-colors">${Object.entries({bg:'深空背景',nebula:'星云色',keyword:'主题节点',phenomenon:'交汇观点',answer:'回答 / 全息',ink:'正文文字',trail:'探索航迹'}).map(([k,label])=>`<label>${label}<input type="color" data-color="${k}"></label>`).join('')}</div><p class="zg-contrast-note"></p>${range('glow','节点光晕强度',0,1.3)}${range('starDensity','背景星点密度',0,1.5)}<button type="button" data-action="theme-export">导出当前配色 JSON</button><button type="button" data-action="theme-import">导入配色</button></section>
      <section data-section="ai" hidden><div class="zg-ai-intro"><span>01 扫描词语</span><span>02 本地候选</span><span>03 原文复核</span></div><p class="zg-hint">先展示本地结果。AI 一次扫描现有标签，只修明显不合适的词；宽松相似度召回后，仍按你选的最多赞 / 最新 / 随机排序，批量交给 AI 选出每个修正词最多 8 篇。不会调用一次 API 分析一篇全文。</p><div class="zg-ai-status" role="status"></div><div class="zg-row-actions"><button type="button" data-action="ai-config">供应商与 API Key 设置 ↗</button><button type="button" data-action="ai-refresh">刷新连接状态</button></div><p class="zg-hint">为避免密钥暴露给知乎页面，填写入口在扩展自己的独立设置页。默认关闭；启用并确认授权后才发送标题、关键词及少量原文片段。</p><div class="zg-row-actions"><button type="button" data-action="ai-run" class="zg-primary">校对当前关键词</button><button type="button" data-action="ai-cancel">取消</button><button type="button" data-action="ai-undo">撤销本轮修正</button></div><div class="zg-ai-audit"></div><p class="zg-hint">超时、断网、格式错误或证据不足时，不提交有问题的修正。重新命名保留节点 ID，收藏不受影响；不上传轨迹，不构建画像。</p></section>
      <section data-section="reading" hidden><label>回答优先顺序<select data-setting="sortMode"><option value="votes">最多赞</option><option value="latest">最新</option><option value="random">随机 · 本轮固定顺序</option></select></label><button type="button" data-action="shuffle">换一组随机顺序</button><label>首批预览篇数<input data-setting="previewAfter" type="number" min="3" max="50"></label><label>每批新增回答<input data-setting="batchSize" type="number" min="3" max="30"></label><label>本次读取上限<input data-setting="maxAnswers" type="number" min="10" max="500"></label><label>文字尺寸<select data-setting="fontScale"><option value="1">标准</option><option value="1.15">大字</option><option value="1.3">更大</option></select></label>${checkbox('autoFocus','点击节点时平移视野到中央（不自动旋转）')}${checkbox('recordTrail','记录本机轨迹（关闭后仍可主动收藏）')}${checkbox('showTrail','显示空间中的探索航迹')}<p class="zg-hint">最多赞 / 最新 / 随机是一套全局顺序：加载、关联列表和 AI 候选共用。随机只对已取得的回答池洗牌，不代表全站随机抽样。</p></section>
      <div class="zg-settings-bottom"><button type="button" data-action="apply-settings" class="zg-primary">应用并保存</button><small>关闭 × 撤销未保存的参数预览；已执行的 AI 修正需单独撤销。</small></div></form>`;
    const colorImport=document.createElement('input');colorImport.type='file';colorImport.accept='.json,application/json';colorImport.hidden=true;colorImport.className='zg-color-file';this.root.appendChild(colorImport);
    this.frontCanvas=document.createElement('canvas');this.frontCanvas.className='zg-occlusion';this.frontCanvas.setAttribute('aria-hidden','true');this.root.appendChild(this.frontCanvas);this.frontCtx=this.frontCanvas.getContext('2d');
    const noteDialog=document.createElement('dialog');noteDialog.className='zg-note-dialog';noteDialog.innerHTML='<form method="dialog"><div class="zg-settings-head"><div><b data-note-title>仔细阅读</b><small>右键节点后记录你的想法，回答节点会同步到行囊笔记。</small></div><button value="cancel" aria-label="关闭">×</button></div><label class="zg-checkbox"><input type="checkbox" data-note-read checked>标记为仔细阅读</label><textarea data-note-body rows="7" placeholder="在这里写下你的评论、联想或后续行动…"></textarea><div class="zg-row-actions"><button type="button" data-action="note-save" class="zg-primary">保存记录</button><button type="button" data-action="note-cancel">取消</button></div></form>';this.root.appendChild(noteDialog);
    this.listen(this.$('.zg-settings'),'input',e=>this.previewSetting(e));
    this.listen(this.$('.zg-settings'),'close',()=>{if(this.settingsBeforeDialog&&!this.dialogAccepted){this.settings=this.settingsBeforeDialog;this.applyAppearance();this.physics?.configure(this.settings);}this.settingsBeforeDialog=null;this.dialogAccepted=false;});
    this.listen(colorImport,'change',async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>12000)throw new Error('配色文件过大');const value=JSON.parse(await file.text());if(value.schemaVersion!==1||!value.palette)throw new Error('不是星系配色文件');this.settings.customPalette=S.cleanSettings({customPalette:value.palette}).customPalette;this.settings.theme='custom';this.applyAppearance();this.populateSettings();}catch(err){this.toast(err.message);}finally{e.target.value='';}});
    this.listen(noteDialog,'close',()=>{this.pendingNoteNode=null;});
    this.listen(this.canvas,'contextmenu',e=>{e.preventDefault();const r=this.canvas.getBoundingClientRect(),hits=this.findHits({x:e.clientX-r.left,y:e.clientY-r.top});if(hits[0])this.openNodeNote(hits[0].node);});this.listen(window,'focus',()=>this.loadAIConfig());
    queueMicrotask(()=>this.ready?.then(()=>{this.loadAIConfig();this.loadNodeNotes?.();}));
  };
  P.indexGraph=function(){base.indexGraph.call(this);this.graphEpoch=(this.graphEpoch||0)+1;if(this.physics)this.physics.setNodes(this.nodes);else this.physics=new S.ForceLayout(this.nodes,this.settings);this.refreshNodeColors?.();this.layoutKey=null;};
  P.resize=function(){base.resize.call(this);if(this.frontCanvas){const d=Math.min(2,devicePixelRatio||1);this.frontCanvas.width=this.w*d;this.frontCanvas.height=this.h*d;this.frontCtx.setTransform(d,0,0,d,0,0);}this.layoutKey=null;};
  P.applyAppearance=function(){this.settings=S.cleanSettings(this.settings);base.applyAppearance.call(this);this.palette=S.palette(this.settings);const p=this.palette;for(const k of ['bg','surface','line','muted','ink','keyword','phenomenon','answer','trail','nebula','hover'])this.root.style.setProperty('--zg-'+k,p[k]);this.root.style.setProperty('--zg-teal',p.answer);this.root.style.setProperty('--zg-holo-bg',rgba(p.bg,this.settings.holoOpacity));this.root.style.setProperty('--zg-holo-border',rgba(p.answer,.52));this.root.style.setProperty('--zg-holo-shadow',rgba(p.answer,.1*this.settings.glow));this.root.style.setProperty('--zg-bg-alpha',rgba(p.bg,.90));this.root.style.setProperty('--zg-panel-alpha',rgba(p.surface,.97));this.root.style.setProperty('--zg-accent-faint',rgba(p.answer,.07));this.root.style.setProperty('--zg-accent-medium',rgba(p.answer,.19));this.root.style.setProperty('--zg-glow-scale',this.settings.glow);this.root.dataset.theme=this.settings.theme;this.root.style.colorScheme=S.luminance(p.bg)>.35?'light':'dark';this.$('.zg-reading-dock').hidden=!this.settings.showReadingDock;
    this.refreshNodeColors?.();this.$('.zg-freeze-button').textContent=this.settings.layoutFrozen?'解冻空间':'冻结空间';this.$('.zg-freeze-button').setAttribute('aria-pressed',String(this.settings.layoutFrozen));this.$('.zg-contrast-note').textContent=p.inkAdjusted?'自定义正文色与背景对比不足，阅读正文已自动改为高对比色。':'正文 / 背景对比度 '+S.contrast(p.bg,p.ink).toFixed(1)+' : 1';const forceKey=['attraction','repulsion','nodeScale','answerScale','layoutFrozen'].map(k=>this.settings[k]).join(':');if(this.physics&&forceKey!==this.lastForceKey){this.physics.configure(this.settings);this.lastForceKey=forceKey;}this.layoutKey=null;this.dirty=true;
  };
  const toneBlend=colors=>{const list=(colors||[]).filter(Boolean);if(!list.length)return null;let cur=list[0];for(let i=1;i<list.length;i++)cur=mix(cur,list[i],1/(i+1));return cur;};
  const themeSwatches=settings=>{const p=settings.theme==='custom'?settings.customPalette:(S.PALETTES[settings.theme]||S.PALETTES.tech);return[p.keyword,p.phenomenon,p.answer,mix(p.keyword,p.answer,.52),mix(p.phenomenon,p.answer,.48)];};
  const keywordTone=(id,settings)=>{const sw=themeSwatches(settings),h=S.hash('kw:'+id),a=sw[h%sw.length],b=sw[(h>>>3)%sw.length],t=.18+((h>>>9)%58)/100;return mix(a,b,t);};
  P.refreshNodeColors=function(){const palette=this.palette||S.palette(this.settings),mode=this.settings.nodeColorMode||'uniform',colors=new Map();const put=(id,primary,secondary)=>colors.set(id,{primary:primary||palette.answer,secondary:secondary||null,text:primary||palette.answer});if(!this.nodes?.length){this.nodeColors=colors;return colors;}if(mode!=='lineage'){for(const n of this.nodes)put(n.id,palette[n.type]||palette.answer,null);this.nodeColors=colors;return colors;}
    for(const k of this.graph.keywords||[])put(k.id,keywordTone(k.id,this.settings),null);
    for(const p of this.graph.phenomena||[]){const linked=(p.parents||[]).map(id=>colors.get(id)?.primary).filter(Boolean),primary=toneBlend(linked)||palette.phenomenon,secondary=linked[1]||linked[0]||mix(primary,palette.answer,.35);put(p.id,primary,secondary);}
    for(const a of this.graph.satellites||[]){let related=[];if(a.parent)related.push(a.parent);for(const id of a.links||[])related.push(id);related=related.map(id=>colors.get(id)?.primary).filter(Boolean);const primary=related.length?(a.links?.length?related[S.hash(a.id)%related.length]:toneBlend(related)||related[0]):palette.answer;put(a.id,primary,null);}
    this.nodeColors=colors;return colors;};
  P.nodePaint=function(n){if(!this.nodeColors)this.refreshNodeColors();return this.nodeColors?.get(n.id)||{primary:(this.palette?.[n.type]||this.palette?.answer||'#72e4dc'),secondary:null,text:(this.palette?.[n.type]||this.palette?.answer||'#72e4dc')};};
  P.adjacentIds=function(n){if(!n)return new Set();const ids=new Set([n.id]);if(n.parent)ids.add(n.parent);for(const id of n.parents||[])ids.add(id);for(const id of n.links||[])ids.add(id);for(const other of this.nodes||[]){if(other.parent===n.id||(other.parents||[]).includes(n.id)||(other.links||[]).includes(n.id))ids.add(other.id);if(n.parent&&other.type==='answer'&&other.parent===n.parent&&other.id!==n.id)ids.add(other.id);}return ids;};
  P.loadNodeNotes=async function(){if(this.nodeNotes)return this.nodeNotes;try{if(globalThis.chrome?.storage?.local){const key='zhihuGalaxyNodeNotes';this.nodeNotes=(await chrome.storage.local.get(key))[key]||{};}else this.nodeNotes=JSON.parse(localStorage.getItem('__zg_node_notes__')||'{}');}catch{this.nodeNotes={};}return this.nodeNotes;};
  P.persistNodeNotes=async function(){try{if(globalThis.chrome?.storage?.local)await chrome.storage.local.set({zhihuGalaxyNodeNotes:this.nodeNotes||{}});else localStorage.setItem('__zg_node_notes__',JSON.stringify(this.nodeNotes||{}));}catch{}};
  P.noteKey=function(n){return `${this.questionInfo().id}:${n.id}`;};
  P.openNodeNote=async function(n){if(!n)return;this.pendingNoteNode=n;this.focus(n,{source:'context'});const dialog=this.$('.zg-note-dialog');if(!dialog)return;const body=dialog.querySelector('[data-note-body]'),read=dialog.querySelector('[data-note-read]');await this.loadNodeNotes();const saved=this.nodeNotes[this.noteKey(n)]||{};dialog.querySelector('[data-note-title]').textContent=`仔细阅读 · ${n.label||'节点'}`;body.value=saved.note??'';if(!body.value&&n.type==='answer'){const answer=this.graph.byAnswer.get(n.answerId);body.value=this.holoQuote(answer).replace(/…$/,'').trim();}read.checked=saved.read!==false;dialog.showModal();body.focus();body.select();};
  P.saveCurrentNodeNote=async function(){const n=this.pendingNoteNode,dialog=this.$('.zg-note-dialog');if(!n||!dialog)return;const body=dialog.querySelector('[data-note-body]'),read=dialog.querySelector('[data-note-read]');await this.loadNodeNotes();this.nodeNotes[this.noteKey(n)]={note:body.value.trim(),read:!!read.checked,label:n.label,type:n.type,updatedAt:new Date().toISOString()};await this.persistNodeNotes();if(n.type==='answer'){const answer=this.graph.byAnswer.get(n.answerId);if(answer){const existing=this.state.bookmarks.find(b=>b.questionId===this.questionInfo().id&&String(b.answerId)===String(answer.id));if(!existing)await this.saveBookmark(answer,this.holoQuote(answer).replace(/…$/,'').trim(),'selection');const bookmark=this.state.bookmarks.find(b=>b.questionId===this.questionInfo().id&&String(b.answerId)===String(answer.id));if(bookmark)await this.mutate({type:'bookmark.update',payload:{id:bookmark.id,note:body.value.trim(),tags:bookmark.tags||[]}});}}this.record('visit',n,'careful-read');dialog.close();this.toast('已记录仔细阅读备注');this.dirty=true;};
  P.focus=function(n,opts={}){base.focus.call(this,n,opts);this.selectedFamilyIds=n?this.adjacentIds(n):null;};
  P.home=function(){this.selectedFamilyIds=null;return base.home.call(this);};
  const backImpl=P.back;P.back=function(){backImpl.call(this);this.selectedFamilyIds=this.selected?this.adjacentIds(this.selected):null;};
  P.frameNodeCluster=function(n){if(!n?.pos)return;const nodes=[...this.adjacentIds(n)].map(id=>this.nodeById(id)).filter(Boolean),distances=nodes.map(x=>Math.hypot((x.pos?.x||0)-n.pos.x,(x.pos?.y||0)-n.pos.y,(x.pos?.z||0)-n.pos.z));const maxDist=Math.max(4,...distances);this.center(n);this.targetRadius=clamp(30+maxDist*6.5,26,160);if(this.reduced)this.radius=this.targetRadius;this.syncSlider();this.dirty=true;};
  P.populateSettings=function(){for(const [k,v]of Object.entries(this.settings)){const el=this.$(`[data-setting="${k}"]`);if(el){if(el.type==='checkbox')el.checked=!!v;else el.value=String(v);}const out=this.$(`[data-for="${k}"]`);if(out)out.textContent=Number.isInteger(v)?String(v):Number(v).toFixed(2);}
    const p=S.palette(this.settings);for(const el of this.root.querySelectorAll('[data-color]'))el.value=(this.settings.theme==='custom'?this.settings.customPalette:p)[el.dataset.color];for(const el of this.root.querySelectorAll('[data-action="theme"]'))el.setAttribute('aria-pressed',String(el.dataset.value===this.settings.theme));this.refreshAIUI();
  };
  P.previewSetting=function(e){const k=e.target.dataset.setting;if(k){const value=e.target.type==='checkbox'?e.target.checked:e.target.type==='range'||e.target.type==='number'?Number(e.target.value):e.target.value;this.settings=S.cleanSettings({...this.settings,[k]:value});const out=this.$(`[data-for="${k}"]`);if(out)out.textContent=Number.isInteger(value)?String(value):Number(value).toFixed(2);if(['attraction','repulsion','nodeScale','answerScale','layoutFrozen'].includes(k))this.physics?.configure(this.settings);if(k==='sortMode'){this.lastPreviewRefresh=0;this.cancelAI?.('优先顺序变化，请按新顺序重新校对');}}
    const color=e.target.dataset.color;if(color){this.settings.customPalette={...S.palette(this.settings),[color]:e.target.value};this.settings.theme='custom';}this.applyAppearance();
  };
  P.applySettings=async function(){for(const el of this.root.querySelectorAll('[data-setting]'))this.settings[el.dataset.setting]=el.type==='checkbox'?el.checked:el.type==='range'||el.type==='number'?Number(el.value):el.value;this.settings=S.cleanSettings(this.settings);this.dialogAccepted=true;this.$('.zg-settings').close();this.applyAppearance();this.physics?.configure(this.settings);this.keys.clear();try{await this.mutate({type:'settings',payload:this.settings});await this.options.onSettingsChange?.(this.settings,this);this.toast('星系参数已保存 · 布局在三维空间中舒展');}catch(e){this.toast('保存失败：'+e.message,5000);}this.lastPreviewRefresh=0;};
  P.switchSettingsTab=function(tab){for(const sec of this.root.querySelectorAll('[data-section]'))sec.hidden=sec.dataset.section!==tab;for(const b of this.root.querySelectorAll('[data-action="settings-tab"]'))b.setAttribute('aria-pressed',String(b.dataset.value===tab));this.refreshAIUI();};
  P.action=async function(e){const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;this.lastUserAt=Date.now();try{
      if(a==='settings'||a==='ai-tab'){this.settingsBeforeDialog=C.clone(this.settings);this.dialogAccepted=false;this.populateSettings();this.keys.clear();this.$('.zg-settings').showModal();this.switchSettingsTab(a==='ai-tab'?'ai':'space');this.loadAIConfig();return;}
      if(a==='settings-tab'){this.switchSettingsTab(el.dataset.value);return;}
      if(a==='freeze'){this.settings.layoutFrozen=!this.settings.layoutFrozen;this.physics.configure(this.settings);this.applyAppearance();await this.mutate({type:'settings',payload:this.settings});return;}
      if(a==='relayout'){this.settings.layoutFrozen=false;this.physics.configure(this.settings);this.physics.wake(300);this.populateSettings();this.applyAppearance();return;}
      if(a==='reset-space'){for(const k of ['attraction','repulsion','nodeScale','answerScale','rotationSpeed','zoomSpeed','holoScale','holoOpacity','cardCount','layoutFrozen','motion'])this.settings[k]=S.DEFAULT[k];this.physics.configure(this.settings);this.populateSettings();this.applyAppearance();return;}
      if(a==='theme'){this.settings.theme=el.dataset.value;this.settings.customPalette={...S.PALETTES[el.dataset.value]};this.populateSettings();this.applyAppearance();return;}
      if(a==='theme-export'){this.download(JSON.stringify({schemaVersion:1,name:this.settings.theme,palette:Object.fromEntries(Object.keys(S.DEFAULT.customPalette).filter(k=>k!=='name').map(k=>[k,S.palette(this.settings)[k]]))},null,2),'application/json','zhihu-galaxy-palette.json');return;}
      if(a==='theme-import'){this.$('.zg-color-file').click();return;}
      if(a==='shuffle'){this.cancelAI?.('随机顺序变化，请按新顺序重新校对');this.settings.sortMode='random';this.settings.randomSeed=(S.hash(String(Date.now()))%2147483646)+1;this.populateSettings();this.toast('已换随机种子；应用后加载、列表、AI 共用此顺序');return;}
      if(a==='save-holo'){const answer=this.graph.byAnswer.get(el.dataset.answerId);if(answer)await this.saveBookmark(answer,this.holoQuote(answer).replace(/…$/, '').trim(),'selection');return;}
      if(a==='note-save'){await this.saveCurrentNodeNote();return;}
      if(a==='note-cancel'){this.$('.zg-note-dialog')?.close();return;}
      if(a==='ai-config'){if(!globalThis.chrome?.runtime?.id){this.toast('请加载扩展后，在扩展自己的设置页填写 API Key；普通演示网页不能保存密钥',6000);return;}await this.aiSend('OPEN');return;}
      if(a==='ai-refresh'){await this.loadAIConfig();return;}
      if(a==='ai-run'){await this.runAI();return;}
      if(a==='ai-cancel'){this.cancelAI();return;}
      if(a==='ai-undo'){this.undoAI();return;}
    }catch(err){this.toast(err.message,5500);return;}return base.action.call(this,e);
  };
  P.pointerDown=function(e){if(e.button!==0&&e.button!==1)return;this.canvas.focus({preventScroll:true});this.drag={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false,pan:e.button===1};this.canvas.setPointerCapture(e.pointerId);this.lastUserAt=Date.now();};
  P.pointerMove=function(e){const rect=this.canvas.getBoundingClientRect();this.pointerAt={x:e.clientX-rect.left,y:e.clientY-rect.top};this.lastUserAt=Date.now();if(this.drag){const d=this.drag,dx=clamp(e.clientX-d.lastX,-70,70),dy=clamp(e.clientY-d.lastY,-70,70);d.lastX=e.clientX;d.lastY=e.clientY;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>4)d.moved=true;if(d.moved){if(d.pan){this.prepareProjection();const s=this.radius/this.focal;this.look=add(add(this.look,this.right,-dx*s),this.up,dy*s);}else if(this.settings.motion!=='still'){const speed=.0026*this.settings.rotationSpeed*(this.settings.motion==='explore'?1.35:1);this.theta-=dx*speed;this.phi=clamp(this.phi+dy*speed,.08,Math.PI-.08);}this.cameraAnim=null;this.hover=null;this.dirty=true;}return;}base.pointerMove.call(this,e);};
  P.pointerUp=function(e){const d=this.drag;if(!d)return;this.drag=null;try{this.canvas.releasePointerCapture(e.pointerId);}catch{}if(d.moved)return;const r=this.canvas.getBoundingClientRect(),hits=this.findHits({x:e.clientX-r.left,y:e.clientY-r.top});if(e.button===1){if(hits.length>1&&Math.abs(hits[0].distance-hits[1].distance)<8){this.showCluster(hits.slice(0,12).map(x=>x.node));return;}return;}const hit=hits[0];if(!hit)return;const now=performance.now(),same=this.lastTap?.id===hit.node.id&&now-(this.lastTap?.at||0)<280;this.lastTap={id:hit.node.id,at:now};if(same){this.focus(hit.node,{source:'pointer',center:true});this.frameNodeCluster(hit.node);return;}this.focus(hit.node,{source:'pointer'});};
  P.keydown=function(e){base.keydown.call(this,e);const tag=document.activeElement?.tagName;if(tag&&/^(INPUT|TEXTAREA|SELECT)$/i.test(tag))return;if(e.metaKey||e.ctrlKey||e.altKey)return;if(e.code==='Space'){e.preventDefault();this.keys.add(' ');}if(e.key==='Shift')this.keys.add('shift');};
  P.wheel=function(e){e.preventDefault();const unit=e.deltaMode===1?16:e.deltaMode===2?this.h:1,delta=clamp(e.deltaY*unit,-150,150);this.targetRadius=clamp(this.targetRadius*Math.exp(delta*.0014*this.settings.zoomSpeed),26,240);if(this.reduced)this.radius=this.targetRadius;this.cameraAnim=null;this.lastUserAt=Date.now();this.dirty=true;};
  P.syncSlider=function(){if(this.slider)this.slider.value=String(clamp(Math.log(this.radius/240)/Math.log(26/240)*100,0,100));};
  // Replace the v0.6 range listener with one authoritative distance map using capture phase.
  const oldRender=P.renderShell;P.renderShell=function(){oldRender.call(this);this.listen(this.slider,'input',e=>{e.stopImmediatePropagation();this.targetRadius=240*Math.pow(26/240,Number(this.slider.value)/100);if(this.reduced)this.radius=this.targetRadius;this.cameraAnim=null;this.dirty=true;this.lastUserAt=Date.now();},{capture:true});};
  P.update=function(dt,t){let moving=false;const speed=.53*this.settings.rotationSpeed*(this.settings.motion==='explore'?1.35:1);if(this.settings.motion!=='still'){if(this.keys.has('a')){this.theta-=speed*dt;moving=true;}if(this.keys.has('d')){this.theta+=speed*dt;moving=true;}if(this.keys.has('w')){this.phi-=speed*.7*dt;moving=true;}if(this.keys.has('s')){this.phi+=speed*.7*dt;moving=true;}}if(this.keys.has(' ')){this.targetRadius=clamp(this.targetRadius+72*dt*this.settings.zoomSpeed,26,240);moving=true;}if(this.keys.has('shift')){this.targetRadius=clamp(this.targetRadius-72*dt*this.settings.zoomSpeed,26,240);moving=true;}this.phi=clamp(this.phi,.08,Math.PI-.08);if(moving){this.cameraAnim=null;this.lastUserAt=Date.now();this.hover=null;}
    if(Math.abs(this.radius-this.targetRadius)>.01){this.radius=this.reduced?this.targetRadius:this.radius+(this.targetRadius-this.radius)*(1-Math.exp(-dt/.105));moving=true;this.syncSlider();}else this.radius=this.targetRadius;
    if(this.cameraAnim){const a=this.cameraAnim,q=clamp((t-a.start)/a.duration,0,1),u=1-(1-q)**3;this.look={x:a.from.x+(a.to.x-a.from.x)*u,y:a.from.y+(a.to.y-a.from.y)*u,z:a.from.z+(a.to.z-a.from.z)*u};moving=true;if(q>=1)this.cameraAnim=null;}
    // Settle only after a parameter/graph change; never keep the map in perpetual motion.
    if(this.physics?.steps&&!this.settings.layoutFrozen&&!this.previewHold&&!this.drag&&!getSelection()?.toString()){if(this.reduced){this.physics.settle(120);moving=true;}else moving=this.physics.step(dt)||moving;}return moving;
  };
  P.buildScreen=function(){const key=[this.theta,this.phi,this.radius,this.look.x,this.look.y,this.look.z,this.w,this.h,this.physics?.revision,this.graphEpoch,this.settings.nodeScale,this.settings.answerScale].join(':');if(key===this.layoutKey)return;this.layoutKey=key;this.prepareProjection();const raw=[];for(const node of this.nodes){const p=this.project(node.pos);if(!p||p.x<-50||p.x>this.w+50||p.y<-50||p.y>this.h+50)continue;const r=clamp(S.worldRadius(node,this.settings)*p.scale,.75,38);raw.push({...p,r,id:node.id,node});}this.screen=raw;this.screenMap=new Map(raw.map(p=>[p.id,p]));this.metrics.projectionShift=0;};
  P.chooseAttention=function(t){const bounds=this.viewBounds(),center={x:this.w*.49,y:this.h*.52};let candidates=this.screen.filter(p=>p.node.type==='answer'&&this.isRelevant(p.node)&&(!this.search||this.matches.has(p.id))&&p.x>=bounds.x&&p.x<=bounds.x+bounds.w&&p.y>=bounds.y&&p.y<=bounds.y+bounds.h);
    candidates.sort((a,b)=>{const priority=p=>(this.isBranch(p.node)?-150:0)+(p.node.aiSelected?-20:0)+Math.hypot(p.x-center.x,p.y-center.y)*.55+Math.max(0,p.z-100)*.15;return priority(a)-priority(b)||S.compareAnswers(this.graph.byAnswer.get(a.node.answerId),this.graph.byAnswer.get(b.node.answerId),this.settings);});this.previewCandidates=candidates;
    const hover=this.hover?.type==='answer'&&t-(this.hoverSince||0)>100?this.hover.id:null,explicit=this.previewHold||hover||(this.selected?.type==='answer'?this.selected.id:null),active=this.preview.update({now:t,explicit,candidate:candidates[0]?.id||null,validIds:this.validAnswerIds});
    // A roomy ranked candidate queue is pruned by visibility/occlusion, never relocated in 2D.
    if(t-this.lastPreviewRefresh>1800||this.lastActive!==active||!this.cardsIds.length){const wanted=[],seen=new Set(),addCandidate=id=>{const p=this.screenMap.get(id),a=p&&this.graph.byAnswer.get(p.node.answerId);if(!a||!this.isRelevant(p.node)||wanted.includes(id))return;const text=this.holoQuote(a).replace(/[\s\p{P}]/gu,'');if(seen.has(text))return;seen.add(text);wanted.push(id);};addCandidate(active);for(const id of this.cardsIds||[])addCandidate(id);for(const p of candidates)addCandidate(p.id);if(!this.previewHold&&!getSelection()?.toString())this.cardsIds=wanted.slice(0,40);this.lastPreviewRefresh=t;this.lastActive=active;}this.updateDock();
  };
  P.holoQuote=function(a){const n=this.answerNodes?.get(a?.id);return n?.aiQuote&&a.text.includes(n.aiQuote)?n.aiQuote:this.lead(a);};
  P.drawBackground=function(){const c=this.ctx,p=this.palette;c.fillStyle=p.bg;c.fillRect(0,0,this.w,this.h);const core=this.project({x:0,y:0,z:0})||{x:this.w*.5,y:this.h*.5},g=c.createRadialGradient(core.x,core.y,5,core.x,core.y,Math.max(this.w,this.h)*.62);g.addColorStop(0,rgba(p.nebula,.36));g.addColorStop(.45,rgba(p.nebula,.10));g.addColorStop(1,rgba(p.bg,0));c.fillStyle=g;c.fillRect(0,0,this.w,this.h);
    if(!this.spaceStars)this.spaceStars=Array.from({length:360},(_,i)=>{const h=S.hash(this.questionInfo().id+':star:'+i),y=1-2*(i+.5)/360,r=Math.sqrt(1-y*y),a=i*2.399963+((h%1000)/1000);return{x:Math.cos(a)*r*370,y:y*370,z:Math.sin(a)*r*370,b:.2+((h>>>8)%50)/100,s:.4+((h>>>16)%80)/100};});
    const count=Math.round(190*this.settings.starDensity);for(const star of this.spaceStars.slice(0,count)){let pp;if(this.settings.motion==='explore'&&!this.reduced)pp=this.project(star);else{const h=S.hash(`${star.x}`);pp={x:(h%10000)/10000*this.w,y:((h>>>10)%10000)/10000*this.h};}if(!pp||pp.x<0||pp.x>this.w||pp.y<0||pp.y>this.h)continue;c.fillStyle=rgba(p.ink,star.b*.6);c.fillRect(pp.x,pp.y,star.s,star.s);} // No twinkle, no auto orbit.
  };
  P.drawEdges=function(){const c=this.ctx,p=this.palette,core=this.project({x:0,y:0,z:0}),selected=this.selectedFamilyIds;c.lineWidth=.8;for(const n of this.nodes){const from=this.project(n.pos);if(!from)continue;const parents=n.type==='keyword'?['__core']:n.type==='phenomenon'?(n.parents||[]):[n.parent].filter(Boolean);for(const id of parents){const target=(id==='__core'||id==='__question__')?core:this.nodeById(id)&&this.project(this.nodeById(id).pos);if(!target)continue;const parentNode=id==='__core'?null:this.nodeById(id),baseTone=toneBlend([this.nodePaint(n).primary,parentNode?this.nodePaint(parentNode).primary:null])||this.nodePaint(n).primary,emphasize=!selected||selected.has(n.id)||selected.has(id),alpha=emphasize?(n.type==='keyword' ? .20 : (n.type==='phenomenon' ? .18 : .16)):.04;c.strokeStyle=rgba(baseTone,alpha);c.beginPath();c.moveTo(from.x,from.y);c.lineTo(target.x,target.y);c.stroke();}}if(core){const r=clamp(1.95*core.scale,5,27),glow=r*(4+this.settings.glow*3),g=c.createRadialGradient(core.x,core.y,1,core.x,core.y,glow);g.addColorStop(0,rgba(p.keyword,.35));g.addColorStop(.45,rgba(p.phenomenon,.14*this.settings.glow));g.addColorStop(1,rgba(p.keyword,0));c.fillStyle=g;c.beginPath();c.arc(core.x,core.y,glow,0,Math.PI*2);c.fill();c.fillStyle=p.ink;c.beginPath();c.arc(core.x,core.y,r*.68,0,Math.PI*2);c.fill();c.strokeStyle=rgba(p.keyword,.46);c.beginPath();c.ellipse(core.x,core.y,r*3.3,r*.85,-.3,0,Math.PI*2);c.stroke();c.font=`500 ${clamp(11+core.scale,13,18)}px ${F}`;c.fillStyle=p.ink;c.textAlign='center';c.fillText('问题星核',core.x,core.y+r+23);}};
  P.drawTrail=function(){if(!this.settings.showTrail)return;const c=this.ctx,p=this.palette,events=this.state.events.filter(e=>e.questionId===this.questionInfo().id&&e.kind==='visit').slice(-90);let prev=null;c.save();for(let i=0;i<events.length;i++){const e=events[i],node=this.nodeById(e.node.id),pos=node?.pos;if(prev&&pos&&e.sessionId===prev.e.sessionId){const a=prev.pos,b=pos,offset=norm(cross(sub(b,a),{x:0,y:1,z:0})),bend=Math.min(12,Math.hypot(b.x-a.x,b.y-a.y,b.z-a.z)*.14);c.beginPath();let started=false;for(let j=0;j<=24;j++){const t=j/24,m={x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:a.z+(b.z-a.z)*t},world=add(m,offset,Math.sin(Math.PI*t)*bend),pt=this.project(world);if(!pt){started=false;continue;}if(!started){c.moveTo(pt.x,pt.y);started=true;}else c.lineTo(pt.x,pt.y);}c.strokeStyle=rgba(p.trail,.18+.38*(i/events.length));c.lineWidth=1.25;c.shadowColor=rgba(p.trail,.35*this.settings.glow);c.shadowBlur=5*this.settings.glow;c.stroke();}prev=pos?{e,pos}:null;}c.restore();};
  P.drawOrb=function(p,c=this.ctx){const n=p.node,pal=this.palette,paint=this.nodePaint(n),color=paint.primary,hover=this.hover?.id===n.id,selected=this.selected?.id===n.id,active=this.preview.active===n.id;let alpha=n.type==='answer' ? .78 : .98;if(!this.isRelevant(n)||(this.search&&!this.matches.has(n.id)))alpha=.12;if(this.selectedFamilyIds&&!this.selectedFamilyIds.has(n.id))alpha*=n.type==='answer' ? .18 : .42;if(selected||hover||active)alpha=1;const r=p.r*(hover?1.18:1);c.save();c.globalAlpha=alpha;const glow=this.settings.glow;if(glow>0){const outer=r*(3.4+glow),g=c.createRadialGradient(p.x,p.y,r*.3,p.x,p.y,outer);g.addColorStop(0,rgba(color,.38*glow));g.addColorStop(.45,rgba(color,.13*glow));g.addColorStop(1,rgba(color,0));c.fillStyle=g;c.beginPath();c.arc(p.x,p.y,outer,0,Math.PI*2);c.fill();}const sphere=c.createRadialGradient(p.x-r*.28,p.y-r*.32,0,p.x,p.y,r);sphere.addColorStop(0,mix(color,pal.ink,.45));sphere.addColorStop(.58,color);sphere.addColorStop(1,mix(paint.secondary||color,pal.bg,.28));c.fillStyle=sphere;c.beginPath();c.arc(p.x,p.y,r,0,Math.PI*2);c.fill();if(n.type==='phenomenon'&&paint.secondary){const band=c.createLinearGradient(p.x-r,p.y-r,p.x+r,p.y+r);band.addColorStop(0,rgba(color,.26));band.addColorStop(1,rgba(paint.secondary,.34));c.fillStyle=band;c.beginPath();c.arc(p.x,p.y,r*.92,0,Math.PI*2);c.fill();}if(selected||hover||active){c.strokeStyle=rgba(color,.62);c.lineWidth=.95;c.beginPath();c.arc(p.x,p.y,r+4,0,Math.PI*2);c.stroke();}if(n.type==='answer'&&this.bookmarked?.has(n.answerId)){c.strokeStyle=pal.trail;c.beginPath();c.moveTo(p.x,p.y-r-6);c.lineTo(p.x+r+6,p.y);c.lineTo(p.x,p.y+r+6);c.lineTo(p.x-r-6,p.y);c.closePath();c.stroke();}c.restore();return r;};
  P.drawNodes=function(){this.hits=[];for(const p of [...this.screen].sort((a,b)=>b.z-a.z)){const r=this.drawOrb(p);this.hits.push({node:p.node,x:p.x,y:p.y,r:r+3,z:p.z});}};
  P.drawLabels=function(bounds,occupied=[]){const c=this.ctx,sorted=[...this.screen].filter(p=>p.node.type!=='answer'||p.id===this.preview.active||p.id===this.hover?.id).sort((a,b)=>(b.id===this.selected?.id?1000:0)+(b.id===this.hover?.id?900:0)-(a.id===this.selected?.id?1000:0)-(a.id===this.hover?.id?900:0)||a.z-b.z);const boxes=[...occupied];let count=0;for(const p of sorted){const n=p.node,label=n.type==='answer'?(this.graph.byAnswer.get(n.answerId)?.author||'回答'):n.label,fs=clamp((n.type==='keyword'?11.5:10)+p.scale*1.45,11,22)*this.settings.fontScale;c.font=`${n.type==='keyword'?550:450} ${fs}px ${F}`;const w=c.measureText(label).width,x=p.x+p.r+7,y=p.y-fs*.60,box={x,y,w:w+4,h:fs*1.35};if(x<bounds.x||x+w>bounds.x+bounds.w||y<bounds.y||y+box.h>bounds.y+bounds.h)continue;const important=n.id===this.hover?.id||n.id===this.selected?.id;if(!important&&boxes.some(b=>C.overlap(b,box,3)))continue;boxes.push(box);c.fillStyle=this.nodePaint(n).text;c.textAlign='left';c.textBaseline='top';c.shadowColor=rgba(this.palette.bg,.95);c.shadowBlur=7;c.fillText(label,x,y);c.shadowBlur=0;const hit=this.hits.find(h=>h.node.id===n.id);if(hit)hit.labelBox=box;count++;if(count>75)break;}this.metrics.labelCount=count;};
  P.renderCallouts=function(bounds,obstacles){const layer=this.$('.zg-callouts'),occupied=[...obstacles],result=[],max=this.settings.cardCount,markerRects=this.screen.filter(p=>p.node.type!=='answer').map(p=>({x:p.x-p.r-4,y:p.y-p.r-4,w:p.r*2+8,h:p.r*2+8}));for(const id of this.cardsIds){if(result.length>=max)break;const n=this.nodeById(id),p=this.screenMap.get(id),a=n&&this.graph.byAnswer.get(n.answerId);if(!p||!a||p.z<18)continue;const quote=this.holoQuote(a),w=clamp(180+quote.length*1.25*this.settings.holoScale,190,340),lines=clamp(Math.ceil(quote.length/20),2,4),h=28+lines*24+14;let box=C.packBox({x:p.x,y:p.y-12},w,h,bounds,[...occupied,...markerRects],this.cardCache.get(id),180);if(!box)box=C.packFreeBox({x:p.x,y:p.y-12},w,h,bounds,[...occupied,...markerRects],this.cardCache.get(id));if(!box)continue;this.cardCache.set(id,box);occupied.push(box);result.push({id,n,p,a,box,quote,active:id===this.preview.active||id===this.previewHold});}
    const wanted=new Set(result.map(x=>x.id));for(const el of [...layer.children])if(!wanted.has(el.dataset.answerId))el.remove();if(this.frontCtx)this.frontCtx.clearRect(0,0,this.w,this.h);for(const item of result){const {id,n,p,a,box,quote,active}=item;let el=layer.querySelector(`[data-answer-id="${CSS.escape(id)}"]`);if(!el){el=document.createElement('article');el.className='zg-quote zg-signal';el.dataset.answerId=id;layer.appendChild(el);}const note=this.nodeColors?.get(id)?.primary||this.palette.answer,key=quote+':'+(a.author||'');if(el._key!==key){el.innerHTML=`<button class="zg-quote-body" data-action="node" data-id="${esc(id)}" data-source="signal">${esc(quote)}</button><div class="zg-quote-meta">${esc(a.author||'知乎用户')}</div>`;el._key=key;}el.classList.toggle('zg-quote-active',active);el.style.setProperty('--signal-color',note);el.style.setProperty('--signal-muted',rgba(note,.72));Object.assign(el.style,{left:`${box.x}px`,top:`${box.y}px`,width:`${box.w}px`,height:`${box.h}px`,zIndex:String(Math.round(100000-p.z*100)),opacity:String(active?1:.9)});const lineY=box.y+box.h-8,isLeft=p.x<=box.x,entryX=isLeft?box.x:box.x+box.w,kinkX=isLeft?box.x-12:box.x+box.w+12;this.ctx.strokeStyle=rgba(note,active ? .62 : .36);this.ctx.lineWidth=active?1.45:1.05;this.ctx.beginPath();this.ctx.moveTo(p.x,p.y);this.ctx.lineTo(kinkX,lineY);this.ctx.lineTo(isLeft?box.x+box.w:box.x,lineY);this.ctx.stroke();}
    this.visibleHolograms=result;this.metrics.summaryCards=result.length;this.metrics.summaryRects=result.map(r=>r.box);this.metrics.cardOverlaps=0;for(let i=0;i<result.length;i++)for(let j=i+1;j<result.length;j++)if(C.overlap(result[i].box,result[j].box))this.metrics.cardOverlaps++;return occupied;};
  P.draw=function(t){this.prepareProjection();this.buildScreen();this.drawBackground();this.chooseAttention(t);this.drawEdges();this.drawTrail();this.drawNodes();const occupied=this.renderCallouts(this.viewBounds(),this.obstacleRects());this.drawLabels(this.viewBounds(),occupied);this.metrics.visibleNodes=this.screen.length;this.metrics.answerNodes=this.graph.satellites.length;this.metrics.worldNodes=this.nodes.length;this.metrics.activePreview=this.preview.active;this.metrics.layoutSteps=this.physics?.steps||0;};
  const oldDirectory=P.showDirectory;P.showDirectory=function(){this.graph.answers.sort((a,b)=>S.compareAnswers(a,b,this.settings));return oldDirectory.call(this);};
  const oldRoute=P.renderRoute;P.renderRoute=function(visits){const p=this.palette;return oldRoute.call(this,visits).replaceAll('#71c4ba',p.answer).replaceAll('#d9bc80',p.trail).replaceAll('#172834',p.surface).replaceAll('#dfebe8',p.ink);};
  P.relatedAnswers=function(node){const ids=new Set(node.answerIds||[]),children=new Set(this.graph.phenomena.filter(p=>p.parents?.includes(node.id)).map(n=>n.id));for(const n of this.graph.satellites)if(n.parent===node.id||children.has(n.parent))ids.add(n.answerId);return [...ids].map(id=>this.graph.byAnswer.get(String(id))).filter(Boolean).sort((a,b)=>S.compareAnswers(a,b,this.settings));};
  P.showPanel=function(n){base.showPanel.call(this,n);if(n?.aiRepair){const aside=document.createElement('div');aside.className='zg-ai-evidence';aside.textContent=`AI 校对：${n.aiRepair.oldLabel} → ${n.label} · ${n.aiEvidenceIds?.length||0} 篇原文复核通过。${n.aiRepair.reason||''}`;this.panel.querySelector('.zg-panel-heading')?.after(aside);const selected=(n.aiEvidenceIds||[]).map(id=>this.graph.byAnswer.get(id)).filter(Boolean).sort((a,b)=>S.compareAnswers(a,b,this.settings));if(selected.length){const details=document.createElement('details');details.className='zg-ai-picks';details.open=true;details.innerHTML='<summary>AI 复核精选 · 不超过 8 篇</summary>'+selected.map(a=>this.answerCard(a)).join('');aside.after(details);}}};
  P.setProgress=function(p){base.setProgress.call(this,p);this.scheduleAI?.();};
  P.replaceQuestion=function(q,meta){this.aiCandidateIndex=null;if(this.aiBusy)this.cancelAI('回答池变化，本轮 AI 结果已作废');base.replaceQuestion.call(this,q,meta);this.scheduleAI();};
  P.destroy=function(){this.cancelAI();clearTimeout(this.aiTimer);base.destroy.call(this);};
  globalThis.ZG3D={version:'0.7.1',renderer:'world-projected-canvas-with-perspective-holograms'};
})();
